**Linda Zier**

**ST 554**

**Project 2**

*03/24/2026*


## Introduction

This project has two parts.  In the first part I have created a data quality class in pyspark. This class is a python class that wraps an SQL DataFrame and provides functionality for cleaning and checking data. I then use myclass on air quality data.

In the second part of the project I analyze data using Spark SQL style dataframes and pandas-on-Spark data frames. The data used for this part of the project is NFL data.

## Part I - Creating a Class

I've created a data folder on my github repository and stored the air quality data there.  This part of the project utilizes the air quality data set available at the UCI Machine Learning Repository (https://archive.ics.uci.edu/dataset/360/air+quality). This data is time series data (data recorded over time) for air quality measurements of pollutants in an Italian city. The dataset consists of 9,358 hourly-averaged observations collected from five metal oxide chemical sensors integrated into an air quality multisensor device. The data were gathered over a one-year period from March 2004 through February 2005 (De Vito, 2008).

The pollutants measured, which are "true" (gold standard) measurements, are the following:

- CO(GT) (CO concentration)
- C6H6(GT) (Benzene concentration)
- NMHC(GT) (Non Metanic HydroCarbon concentration)
- NOx(GT) (NOx concentration)
- NO2(GT) (NO2 concentration)
- T (temperature)
- RH (Relative humidity)
- AH (Absolute Humidity)

I've included this information here because it is important to understand the data you are analyzing, though the focus of this project is to program in Spark SQL, pandas-on-Spark, and pandas. Let's get to it.

In [1]:
# imports 
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd

from pyspark.sql import SparkSession


spark = SparkSession.builder.appName("Project2").config("spark.sql.ansi.enabled", "false").getOrCreate()

WARNING: Using incubator modules: jdk.incubator.vector
Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
Setting default log level to "WARN".
To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
26/03/26 10:00:08 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable

In [2]:
# imports to run when the kernel gets restarted

import Spark_class
from Spark_class import SparkDataCheck

import importlib
importlib.reload(Spark_class)

    After loading the data, I checked the numeric data types for missing values indicated by an entry of -200. I replaced those with None to give NULL values. I also dropped the first column of indexes.  I don't need it and it gives me warnings later because there is no heading to the column.

In [3]:

# Loading the air data using the from_csv method 
air = Spark_class.SparkDataCheck.from_csv(spark, "data/air.csv")
   
#air.df.printSchema(5)

#I see this first column is just index values so I drop it to prevent warnings
air.df=air.df.drop("_c0")

#get numeric columns
numeric_types = ['int', 'bigint', 'float', 'double', 'decimal', 'long', 'short']

#cleaning up : replacing the -200 values with NULL
for c, dtype in air.df.dtypes:
    if dtype in numeric_types:
        air.df=air.df.withColumn(c, F.when(F.col(f'`{c}`')== -200, None).otherwise(F.col(f'`{c}`')))
    
air.df.show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

    In order to test the string methods, I needed to add a few more columns with string variables.  It made sense to quantify temperature and relative humidity. I also needed to ensure the NULL values didn't end up in one of the other categories to falsely record the level.

In [4]:
# making some string columns that hopefully make sense

air.df = air.df.withColumn('T_level',F.when(F.col('T') > 20, 'high').
                           when(F.col('T') > 10, 'medium').when(F.col('T') >= 0, 'low').otherwise(None))

air.df = air.df.withColumn('RH_level',F.when(F.col('RH') > 60,'high').
                           when(F.col('RH')>30, 'medium').when(F.col('RH') >= 0, 'low').otherwise(None))

air.df.show()

#checking to make sure the NULL values don't end up in one of the other categories to falsely record the level
result = air.check_null("RH")
result.df.filter(F.col('null_check') == True).show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|
|3/11/2004|2026-03-26 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|
|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|
|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|
|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|
|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|
|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|
|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|
|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|
|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|
|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
only showing top 20 rows
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
|4/1/2004|2026-03-26 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/1/2004|2026-03-26 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/1/2004|2026-03-26 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/8/2004|2026-03-26 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/9/2004|2026-03-26 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
only showing top 5 rows

### Validation Method Examples
    Below are several examples of using validation methods with my SparkDataCheck class.

**Checking numeric range**
- Here is an example of using my methods on the air quality data to check if it falls between 2 values.

In [5]:
result=air.check_col_range(column="T", lower=10.0, upper=11.1)
result.df.show(10)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|     true|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|     true|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows

- Now I'm showing what happens when you don't have at least a lower or an upper value for the range.

In [6]:
result=air.check_col_range(column="T")
#result.df.show(10)

Need a lower and/or an upper range for T!!!

- Here I've supplied only an upper range in one case and only a lower case in another.

In [7]:
air.check_col_range(column="CO(GT)", upper=2.0)
air.df.show(10)

air.check_col_range(column="NOx(GT)", lower=100)
air.df.show(10)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|    false|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|     true|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|     true|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|     true|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|     true|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows

- Here I've tested something that wasn't one of the number types we specified.

In [8]:
air.check_col_range(column="T_level", lower=0)

Column is not numeric!

In [9]:
# this was a visual for me to see what types I had to work with.
#air.df.dtypes

**Checking for null values**
- First I am checking for NULL values in the T (temperature) column. I'm also filtering on just Null in that column so it's easy to check.

In [10]:
#air.df.toPandas().isnull().sum()

# check for null in T
result=air.check_null(column="T")
result.df.show(10)

result.df.filter(F.col('null_check') == True).show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|num_check|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|4/1/2004|2026-03-26 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|4/1/2004|2026-03-26 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/1/2004|2026-03-26 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/8/2004|2026-03-26 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/9/2004|2026-03-26 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
only showing top 5 rows

In [11]:
# I used this to see counts 
# air.df.toPandas().isnull().sum()

- Below I am checking for NULL values in the RH (relative humidity) column. I also filter on NULL so it's easy to verify.

In [12]:
# check for null in RH
result=air.check_null(column="RH")
result.df.show(10)

result.df.filter(F.col('null_check') == True).show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|num_check|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|4/1/2004|2026-03-26 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|4/1/2004|2026-03-26 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/1/2004|2026-03-26 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/8/2004|2026-03-26 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/9/2004|2026-03-26 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
only showing top 5 rows

- Here I'm checking for null values in the date column.  There are no missing values so this was a good way to verify that it was working.

In [13]:
# check for null in Date
result=air.check_null(column="Date")
result.df.show(10)

result.df.filter(F.col('null_check') == True).show(10)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows
+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+----------+---------+
|Date|Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|  T| RH| AH|T_level|RH_level|null_check|num_check|
+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+----------+---------+
+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+----------+---------+

- Here I'm checking for null values in the Benzene concentration(C6H6(GT)) column.

In [14]:
# check for null in C6H6(GT)
result=air.check_null(column="C6H6(GT)")
result.df.show(10)

result.df.filter(F.col('null_check') == True).show(5)

+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|num_check|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|4/1/2004|2026-03-26 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|4/1/2004|2026-03-26 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/1/2004|2026-03-26 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/8/2004|2026-03-26 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|4/9/2004|2026-03-26 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
only showing top 5 rows

**Checking for string values**

Now I can check if each value in a string column falls within a user specified set of levels and returns the dataframe with an appended column of Boolean values. 
- Below I've checked various string column levels with 4 examples: Temerature level low and medium, and Relative Humidity level high and medium.

In [15]:
# checking string levels

print('\n\n Temp level = low')
air.check_string('T_level', 'low')
air.df.show()

print('\n\n Temp level = medium')
air.check_string('T_level', 'medium')
air.df.show()

print('\n\n RH level = high')
air.check_string('RH_level', 'high')
air.df.show() 

print('\n\n RH level = medium')
air.check_string('RH_level', 'medium')
air.df.show()

 Temp level = low
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|    false|
|3/11/2004|2026-03-26 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|    false|
|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|    false|
|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|    false|
|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|    false|
|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|     true|
|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|     true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows


 Temp level = medium
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|     true|
|3/11/2004|2026-03-26 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|     true|
|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|     true|
|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|     true|
|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|     true|
|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|    false|
|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|    false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows


 RH level = high
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|    false|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|     true|
|3/11/2004|2026-03-26 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|     true|
|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|    false|
|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|     true|
|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|    false|
|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|    false|
|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|     true|
|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|     true|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows


 RH level = medium
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|    false|
|3/11/2004|2026-03-26 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|    false|
|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|     true|
|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|    false|
|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|     true|
|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|    false|
|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|    false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows

- The column RH is not a string so here is an example of giving an error message with strings.

In [16]:

# you can see that these values are the same as previous because RH is not a string
air.check_string('RH', 'medium')
air.df.show()

Column is not a string!
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|3/10/2004|2026-03-26 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|     true|
|3/10/2004|2026-03-26 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|    false|
|3/11/2004|2026-03-26 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|    false|
|3/11/2004|2026-03-26 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|     true|
|3/11/2004|2026-03-26 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|    false|
|3/11/2004|2026-03-26 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|     true|
|3/11/2004|2026-03-26 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|     true|
|3/11/2004|2026-03-26 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|    false|
|3/11/2004|2026-03-26 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|    false|
+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows

### Summarization Method Examples

Below I've given some examples of the summarization methods.

- This summarizes all the numeric columns since no column was entered in the method call.

In [17]:
#min and max of all the numeric columns
air.col_minmax()

26/03/26 10:00:16 WARN SparkStringUtils: Truncated the string representation of a plan since it was too large. This behavior can be adjusted by setting 'spark.sql.debug.maxToStringFields'.

         col_name       min       max
0          CO(GT)    0.1000    11.900
1     PT08.S1(CO)  647.0000  2040.000
2        NMHC(GT)    7.0000  1189.000
3        C6H6(GT)    0.1000    63.700
4   PT08.S2(NMHC)  383.0000  2214.000
5         NOx(GT)    2.0000  1479.000
6    PT08.S3(NOx)  322.0000  2683.000
7         NO2(GT)    2.0000   340.000
8    PT08.S4(NO2)  551.0000  2775.000
9     PT08.S5(O3)  221.0000  2523.000
10              T   -1.9000    44.600
11             RH    9.2000    88.700
12             AH    0.1847     2.231

- Now I summarize four different numeric min-max columns to show functionality. This includes 2 examples of grouped levels.

In [18]:
# CO level min and max
air.col_minmax("CO(GT)")

  col_name  min   max
0   CO(GT)  0.1  11.9

In [19]:
# Benzene grouped by T level
result=air.col_minmax("C6H6(GT)", "T_level")
# added categories so displays properly
result['T_level'] = pd.Categorical(result['T_level'], categories=['low', 'medium', 'high'], ordered=True)
result.sort_values(['T_level'])

   col_name T_level  min   max
0  C6H6(GT)     low  0.1  63.7
3  C6H6(GT)  medium  0.2  50.8
2  C6H6(GT)    high  1.0  52.1
1  C6H6(GT)     NaN  0.2  12.4

In [20]:
# benzene grouped by relative humidity level
result=air.col_minmax("C6H6(GT)", "RH_level")
#making
result['RH_level'] = pd.Categorical(result['RH_level'], categories=['low', 'medium', 'high'], ordered=True)
result.sort_values(['RH_level'])

   col_name RH_level  min   max
0  C6H6(GT)      low  0.9  38.4
3  C6H6(GT)   medium  0.1  63.7
2  C6H6(GT)     high  0.5  52.1
1  C6H6(GT)      NaN  NaN   NaN

- In this case I call a non-numeric column.

In [21]:
air.col_minmax("T_level")

Column T_level is not numeric!


Here I report the counts associated with one or two string columns.
- Below are the temperature counts for each category.

In [22]:
result=air.str_count('T_level')

# making categories for sorting
result['T_level'] = pd.Categorical(result['T_level'], categories=['low', 'medium', 'high'], ordered=True)
result.sort_values(['T_level'])

  T_level  count
0     low   1683
3  medium   3584
2    high   3711
1     NaN    379

- Below are the relative humidity counts for each category. I changed the order to one that is more logical.

In [23]:

result=air.str_count('RH_level')
result['RH_level'] = pd.Categorical(result['RH_level'], categories=['low', 'medium', 'high'], ordered=True)
result.sort_values(['RH_level'])

  RH_level  count
0      low   1441
3   medium   4917
2     high   2633
1      NaN    366

In [24]:

result=air.str_count('RH_level', 'T_level')
result['T_level'] = pd.Categorical(result['T_level'], categories=['low', 'medium', 'high'], ordered=True)
result['RH_level'] = pd.Categorical(result['RH_level'], categories=['low', 'medium', 'high'], ordered=True)
result.sort_values(['RH_level','T_level', ])

   RH_level T_level  count
7       low     low     33
10      low  medium    222
0       low    high   1186
9    medium     low    879
3    medium  medium   1875
4    medium    high   2150
6    medium     NaN     13
8      high     low    771
5      high  medium   1487
2      high    high    375
1       NaN     NaN    366

Now I'll read that same data set in using pandas. Since we are loading the data from its origins, we will need to repeat the data cleaning we did before. That includes replacing -200 values with None and adding string data, dropping the first column, and adding temp and RH levels

In [25]:
# read the file from pandas
air_pd=pd.read_csv("data/air.csv")

# drop the unnamed index column
air_pd = air_pd.drop(columns=air_pd.columns[0])

# replace -200 with null values
air_pd = air_pd.replace(-200, None)

#convert into SDC object
air2 =Spark_class.SparkDataCheck.from_pd(spark, air_pd)

# making some string columns as before

air2.df = air2.df.withColumn('T_level',F.when(F.col('T') > 20, 'high').
                           when(F.col('T') > 10, 'medium').when(F.col('T') >= 0, 'low').otherwise(None))

air2.df = air2.df.withColumn('RH_level',F.when(F.col('RH') > 60,'high').
                           when(F.col('RH')>30, 'medium').when(F.col('RH') >= 0, 'low').otherwise(None))

air2.df.show()

+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|
+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|
|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|
|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|
|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|
|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|
|3/10/2004|23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|
|3/11/2004| 0:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|
|3/11/2004| 1:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|
|3/11/2004| 2:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|
|3/11/2004| 3:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|
|3/11/2004| 4:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|
|3/11/2004| 5:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|
|3/11/2004| 6:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|
|3/11/2004| 7:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|
|3/11/2004| 8:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|
|3/11/2004| 9:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|
|3/11/2004|10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|
|3/11/2004|11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|
|3/11/2004|12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|
|3/11/2004|13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|
+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
only showing top 20 rows

- Here is one example of a method call: in this case Null check is used.

In [26]:
# checking for n ull values
result=air2.check_null("T").df
result.show(5)

#showing just Null to verify
result.filter(result["null_check"] == True).show(5)

+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+
|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|
+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+
|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|
|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|
|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|
|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|
|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|
+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+
only showing top 5 rows
+--------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
|    Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|
+--------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
|4/1/2004|14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/1/2004|15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/1/2004|16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/8/2004|23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|4/9/2004| 0:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
+--------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
only showing top 5 rows

## Part II - Spark SQL and pandas-on-Spark APIs

In this section I'm going to do some basic analysis using two different Spark APIs (Application Programming Interfaces): pandas-on-Spark and Spark SQL. Both allow us to work with large datasets using Spark as the background engine, but pandas-on-Spark mimics the pandas syntax while Spark SQL uses SQL-style commands.  I will perform some analysis on using each of these and note differences along the way.

The data is weekly NFL data. I will be focusing on quarterback stats from the 2005-2023 regular seasons.

### pandas-on-Spark

In this section I use pandas-on-Spark commands to look at the NFL data.

In [27]:
# Spark and pandas imports
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
import pyspark.pandas as ps

ps.set_option('compute.fail_on_ansi_mode', False)
import pandas as pd
import numpy as np

# Read in the .csv file
nfl_df=ps.read_csv("data/weekly_nfl_data.csv")

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/__init__.py:43: UserWarning: 'PYARROW_IGNORE_TIMEZONE' environment variable was not set. It is required to set this environment variable to '1' in both driver and executor sides if you use pyarrow>=2.0.0. pandas-on-Spark will set it for you but it does not work if there is a Spark context already launched.
  warnings.warn(
/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

- Here are the first 5 rows of the dataframe. (I had to double check it because I saw Karim's name on there and couldn't piture a 7'2" running back - different Karim)

In [28]:
# Look at the first 5 rows
nfl_df.head(5)

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

- Once I load data, I like to look at column names and dtypes. Here I look at the columns in the NFL data so I can make meaningful decisions about what stats are of interest.

In [29]:
# look at columns and datatypes in the nfl data

nfl_df.columns
#nfl_df.dtypes

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'opponent_team', 'completions', 'attempts',
       'passing_yards', 'passing_tds', 'interceptions', 'sacks', 'sack_yards',
       'sack_fumbles', 'sack_fumbles_lost', 'passing_air_yards',
       'passing_yards_after_catch', 'passing_first_downs', 'passing_epa',
       'passing_2pt_conversions', 'pacr', 'dakota', 'carries', 'rushing_yards',
       'rushing_tds', 'rushing_fumbles', 'rushing_fumbles_lost',
       'rushing_first_downs', 'rushing_epa', 'rushing_2pt_conversions',
       'receptions', 'targets', 'receiving_yards', 'receiving_tds',
       'receiving_fumbles', 'receiving_fumbles_lost', 'receiving_air_yards',
       'receiving_yards_after_catch', 'receiving_first_downs', 'receiving_epa',
       'receiving_2pt_conversions', 'racr', 'target_share', 'air_yards_share',
       'wopr', 'special_teams_tds', 'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

- Below are quarterback statistics for the regular season from seasons 2005 to 2023.

In [30]:
nfl_seasons_df = nfl_df[(nfl_df["season"] >= 2005) & (nfl_df["season"]<=2023) 
                        & (nfl_df["position"] == "QB")
                        & (nfl_df["season_type"] == "REG")]

nfl_seasons_df.head(5)

        player_id player_name player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr    dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
29406  00-0000722        None          Tony Banks       QB             QB         None         HOU    2005    17         REG            SF           14        25          173.0            1            2.0    0.0        -0.0             0                  0                0.0                        0.0                  7.0    -3.693779                        0   0.0  0.032036        2           -2.0            0              0.0                   0.0                  0.0     0.000000                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            6.72                6.72
29426  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005     9         REG            GB            9        16           65.0            0            1.0    1.0         6.0             1                  0                0.0                        0.0                  4.0    -6.609788                        0   0.0  0.025249        8           14.0            0              0.0                   0.0                  1.0    -1.614163                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            2.00                2.00
29427  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005    10         REG           CLE           13        19          150.0            0            0.0    0.0        -0.0             0                  0                0.0                        0.0                  7.0     5.193222                        0   0.0  0.171917        3           16.0            1              0.0                   0.0                  2.0     0.737467                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0           13.60               13.60
29428  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005    16         REG           CLE            1         1           31.0            1            0.0    0.0        -0.0             0                  0                0.0                        0.0                  1.0     4.662244                        0   0.0       NaN        0            0.0            0              0.0                   0.0                  0.0          NaN                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            5.24                5.24
29447  00-0001335        None          Jeff Blake       QB             QB         None         CHI    2005     2         REG           DET            1         1           11.0            0            0.0    0.0        -0.0             0                  0                0.0                        0.0                  1.0     1.514100                        0   0.0       NaN        1           -1.0            0              0.0                   0.0                  0.0    -2.570310                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            0.34                0.34

 - I then looked at just the columns that include the player_display_name and some key statistics relevant to quarterbacks: season, week, completions, attempts, passing_yards, passing_tds, and interceptions. Based on the slack chat I removed week.

In [31]:
nfl_brief_df = nfl_seasons_df[["player_display_name", "season", "completions",
                               "attempts", "passing_yards", "passing_tds", "interceptions"]]

nfl_brief_df.head(5)

      player_display_name  season  completions  attempts  passing_yards  passing_tds  interceptions
29406          Tony Banks    2005           14        25          173.0            1            2.0
29426       Charlie Batch    2005            9        16           65.0            0            1.0
29427       Charlie Batch    2005           13        19          150.0            0            0.0
29428       Charlie Batch    2005            1         1           31.0            1            0.0
29447          Jeff Blake    2005            1         1           11.0            0            0.0

- For each player_display_name and season combination, I found the sum and mean of each of the statistical quantities  included above.

In [32]:
qb_stats = nfl_brief_df.groupby(["player_display_name", "season"]).agg(
    tot_completions = ("completions", "sum"),
    avg_completions = ("completions", "mean"),
    tot_attempts = ("attempts","sum"),
    avg_attempts = ("attempts", "mean"),
    tot_passing_yards = ("passing_yards", "sum"),
    avg_passing_yards = ("passing_yards", "mean"),
    tot_passing_tds = ("passing_tds", "sum"),
    avg_passing_tds = ("passing_tds", "mean"),
    tot_interceptions = ("interceptions", "sum"),
    avg_interceptions = ("interceptions", "mean"))

qb_stats.head()

                            tot_completions  avg_completions  tot_attempts  avg_attempts  tot_passing_yards  avg_passing_yards  tot_passing_tds  avg_passing_tds  tot_interceptions  avg_interceptions
player_display_name season
Jake Delhomme       2006                263        20.230769           431     33.153846             2805.0         215.769231               17         1.307692               11.0           0.846154
Jake Plummer        2005                277        17.312500           456     28.500000             3366.0         210.375000               18         1.125000                7.0           0.437500
Matt Schaub         2006                 18         3.600000            27      5.400000              208.0          41.600000                1         0.200000                2.0           0.400000
Vince Young         2006                184        12.266667           356     23.733333             2199.0         146.600000               12         0.800000               13.0           0.866667
Kerry Collins       2007                 50         8.333333            82     13.666667              531.0          88.500000                0         0.000000                0.0           0.000000

- Here I've created two new variables (by season/player combination):

    completion_percentage = (sum of completions)/(sum of attempts)

    td_int_ratio = (sum passing tds)/(sum interceptions)
    
    **Because this is pandas-on-Spark, we need to watch out for dividing by zero.**
    In Spark SQL dividing by zero returns NaN. Because this is pandas-on-Spark, this throws an error instead. This is because ANSI mode is enabled as we were warned above.

In [33]:
# creating completion percentage
qb_stats["completion_percentage"]=(qb_stats["tot_completions"]/ 
                                      qb_stats["tot_attempts"].where(qb_stats["tot_attempts"] != 0))

# creating td_int_ratio
qb_stats["td_int_ratio"]=(qb_stats["tot_passing_tds"]/ 
                              qb_stats["tot_interceptions"].where(qb_stats["tot_interceptions"] != 0))

qb_stats.head(20)

                            tot_completions  avg_completions  tot_attempts  avg_attempts  tot_passing_yards  avg_passing_yards  tot_passing_tds  avg_passing_tds  tot_interceptions  avg_interceptions  completion_percentage  td_int_ratio
player_display_name season
Jake Delhomme       2006                263        20.230769           431     33.153846             2805.0         215.769231               17         1.307692               11.0           0.846154               0.610209      1.545455
Jake Plummer        2005                277        17.312500           456     28.500000             3366.0         210.375000               18         1.125000                7.0           0.437500               0.607456      2.571429
Matt Schaub         2006                 18         3.600000            27      5.400000              208.0          41.600000                1         0.200000                2.0           0.400000               0.666667      0.500000
Vince Young         2006                184        12.266667           356     23.733333             2199.0         146.600000               12         0.800000               13.0           0.866667               0.516854      0.923077
Kerry Collins       2007                 50         8.333333            82     13.666667              531.0          88.500000                0         0.000000                0.0           0.000000               0.609756           NaN
Todd Collins        2005                  0         0.000000             0      0.000000                0.0           0.000000                0         0.000000                0.0           0.000000                    NaN           NaN
Charlie Batch       2006                 30         4.285714            52      7.428571              477.0          68.142857                5         0.714286                0.0           0.000000               0.576923           NaN
Eli Manning         2006                301        18.812500           522     32.625000             3244.0         202.750000               25         1.562500               18.0           1.125000               0.576628      1.388889
A.J. Feeley         2006                 26        13.000000            38     19.000000              342.0         171.000000                3         1.500000                0.0           0.000000               0.684211           NaN
Mark Brunell        2006                162        16.200000           261     26.100000             1789.0         178.900000                8         0.800000                4.0           0.400000               0.620690      2.000000
Shaun Hill          2007                 54        18.000000            80     26.666667              501.0         167.000000                5         1.666667                2.0           0.666667               0.675000      2.500000
Aaron Brooks        2006                110        13.750000           192     24.000000             1105.0         138.125000                3         0.375000                8.0           1.000000               0.572917      0.375000
Brett Favre         2006                343        21.437500           613     38.312500             3885.0         242.812500               18         1.125000               18.0           1.125000               0.559543      1.000000
Drew Brees          2007                443        27.687500           655     40.937500             4428.0         276.750000               28         1.750000               18.0           1.125000               0.676336      1.555556
Bruce Gradkowski    2006                177        13.615385           328     25.230769             1661.0         127.769231                9         0.692308                9.0           0.692308               0.539634      1.000000
Matt Hasselbeck     2005                294        18.375000           450     28.125000             3455.0         215.937500               24         1.500000               10.0           0.625000               0.653333      2.400000
Tony Romo           2005                  0         0.000000             0      0.000000                0.0           0.000000                0         0.000000                0.0           0.000000                    NaN           NaN
Patrick Ramsey      2005                 15         3.750000            25      6.250000              279.0          69.750000                1         0.250000                1.0           0.250000               0.600000      1.000000
Tommy Maddox        2005                 34        11.333333            71     23.666667              406.0         135.333333                2         0.666667                4.0           1.333333               0.478873      0.500000
Jamie Martin        2006                 16        16.000000            24     24.000000              208.0         208.000000                1         1.000000                1.0           1.000000               0.666667      1.000000

- Below I've filtered the rows to only include the player-season combinations where the attempts are >50.  Then I've sorted the rows in descending order by completion_percentage and reported the first 40 values!

In [34]:
# filtering on attempts >50 
qb_stats50=qb_stats[qb_stats["tot_attempts"]>50]

#qb_stats50.head(10)

#and then sorting by completion percentage in descending order
qb_best=qb_stats50.sort_values("completion_percentage", ascending=False)

qb_best.head(40)

                            tot_completions  avg_completions  tot_attempts  avg_attempts  tot_passing_yards  avg_passing_yards  tot_passing_tds  avg_passing_tds  tot_interceptions  avg_interceptions  completion_percentage  td_int_ratio
player_display_name season
Drew Brees          2011                471        29.437500           660     41.250000             5535.0         345.937500               46         2.875000               14.0           0.875000               0.713636      3.285714
                    2009                363        24.200000           514     34.266667             4388.0         292.533333               34         2.266667               11.0           0.733333               0.706226      3.090909
Jamie Martin        2005                124        15.500000           177     22.125000             1277.0         159.625000                5         0.625000                7.0           0.875000               0.700565      0.714286
Tony Romo           2010                148        24.666667           213     35.500000             1605.0         267.500000               11         1.833333                7.0           1.166667               0.694836      1.571429
Jim Sorgi           2005                 43         8.600000            62     12.400000              444.0          88.800000                3         0.600000                1.0           0.200000               0.693548      3.000000
Chad Pennington     2009                 51        17.000000            74     24.666667              413.0         137.666667                1         0.333333                2.0           0.666667               0.689189      0.500000
Tom Brady           2007                398        24.875000           578     36.125000             4806.0         300.375000               50         3.125000                8.0           0.500000               0.688581      6.250000
Chad Pennington     2007                179        19.888889           260     28.888889             1766.0         196.222222               10         1.111111                9.0           1.000000               0.688462      1.111111
Peyton Manning      2009                393        24.562500           571     35.687500             4500.0         281.250000               33         2.062500               16.0           1.000000               0.688266      2.062500
Brett Favre         2009                364        22.750000           532     33.250000             4202.0         262.625000               33         2.062500                7.0           0.437500               0.684211      4.714286
David Carr          2006                302        18.875000           442     27.625000             2765.0         172.812500               11         0.687500               12.0           0.750000               0.683258      0.916667
Aaron Rodgers       2011                342        22.800000           501     33.400000             4636.0         309.066667               45         3.000000                6.0           0.400000               0.682635      7.500000
Drew Brees          2010                448        28.000000           658     41.125000             4620.0         288.750000               33         2.062500               22.0           1.375000               0.680851      1.500000
Matt Schaub         2009                396        24.750000           583     36.437500             4770.0         298.125000               29         1.812500               15.0           0.937500               0.679245      1.933333
Carson Palmer       2005                345        21.562500           509     31.812500             3836.0         239.750000               32         2.000000               12.0           0.750000               0.677800      2.666667
Drew Brees          2007                443        27.687500           655     40.937500             4428.0         276.750000               28         1.750000               18.0           1.125000               0.676336      1.555556
Luke McCown         2007                 94        18.800000           139     27.800000             1009.0         201.800000                5         1.000000                3.0           0.600000               0.676259      1.666667
Shaun Hill          2007                 54        18.000000            80     26.666667              501.0         167.000000                5         1.666667                2.0           0.666667               0.675000      2.500000
Chad Pennington     2008                321        20.062500           476     29.750000             3653.0         228.312500               19         1.187500                7.0           0.437500               0.674370      2.714286
Kelly Holcomb       2005                155        15.500000           230     23.000000             1509.0         150.900000               10         1.000000                8.0           0.800000               0.673913      1.250000
Peyton Manning      2005                305        19.062500           453     28.312500             3747.0         234.187500               28         1.750000               10.0           0.625000               0.673289      2.800000
Kurt Warner         2008                402        25.125000           599     37.437500             4582.0         286.375000               30         1.875000               14.0           0.875000               0.671119      2.142857
Marc Bulger         2005                192        24.000000           287     35.875000             2297.0         287.125000               14         1.750000                9.0           1.125000               0.668990      1.555556
Peyton Manning      2008                371        23.187500           555     34.687500             4002.0         250.125000               27         1.687500               12.0           0.750000               0.668468      2.250000
Sage Rosenfels      2008                116        19.333333           174     29.000000             1431.0         238.500000                6         1.000000               10.0           1.666667               0.666667      0.600000
Ben Roethlisberger  2009                337        22.466667           506     33.733333             4328.0         288.533333               26         1.733333               12.0           0.800000               0.666008      2.166667
Brett Favre         2007                356        22.250000           535     33.437500             4157.0         259.812500               28         1.750000               15.0           0.937500               0.665421      1.866667
Matt Schaub         2007                192        17.454545           289     26.272727             2241.0         203.727273                9         0.818182                9.0           0.818182               0.664360      1.000000
Tony Romo           2011                346        21.625000           522     32.625000             4184.0         261.500000               31         1.937500               10.0           0.625000               0.662835      3.100000
Peyton Manning      2010                450        28.125000           679     42.437500             4700.0         293.750000               33         2.062500               17.0           1.062500               0.662739      1.941176
Matt Leinart        2009                 51         6.375000            77      9.625000              435.0          54.375000                0         0.000000                3.0           0.375000               0.662338      0.000000
Kurt Warner         2009                340        22.666667           514     34.266667             3758.0         250.533333               27         1.800000               14.0           0.933333               0.661479      1.928571
Matt Schaub         2008                251        22.818182           380     34.545455             3043.0         276.636364               15         1.363636               10.0           0.909091               0.660526      1.500000
Philip Rivers       2010                357        22.312500           541     33.812500             4710.0         294.375000               30         1.875000               13.0           0.812500               0.659889      2.307692
Tom Brady           2010                324        20.250000           492     30.750000             3900.0         243.750000               36         2.250000                4.0           0.250000               0.658537      9.000000
Jon Kitna           2010                209        20.900000           318     31.800000             2365.0         236.500000               16         1.600000               12.0           1.200000               0.657233      1.333333
Brett Favre         2008                343        21.437500           522     32.625000             3472.0         217.000000               22         1.375000               22.0           1.375000               0.657088      1.000000
Aaron Rodgers       2010                312        20.800000           475     31.666667             3922.0         261.466667               28         1.866667               11.0           0.733333               0.656842      2.545455
Tom Brady           2009                371        23.187500           565     35.312500             4398.0         274.875000               28         1.750000               13.0           0.812500               0.656637      2.153846
                    2011                401        25.062500           611     38.187500             5235.0         327.187500               39         2.437500               12.0           0.750000               0.656301      3.250000


- Below I've filtered the rows to only include the player-season combinations where the attempts are >50. Then I've sorted the rows in descending order by td_int_ratio and reported the first 40 values. I had to drop the NaN rows because they showed up at the top otherwise.

In [35]:
# sorting by best td-to-interceptions ratio in descending order
#had to drop na values because they were at the top which wasn't intended.
qb_best2=qb_stats50.sort_values("td_int_ratio", ascending=False).dropna(subset=["td_int_ratio"])

qb_best2.head(40)

                            tot_completions  avg_completions  tot_attempts  avg_attempts  tot_passing_yards  avg_passing_yards  tot_passing_tds  avg_passing_tds  tot_interceptions  avg_interceptions  completion_percentage  td_int_ratio
player_display_name season
Damon Huard         2006                148        14.800000           244     24.400000             1878.0         187.800000               11         1.100000                1.0           0.100000               0.606557     11.000000
Tom Brady           2010                324        20.250000           492     30.750000             3900.0         243.750000               36         2.250000                4.0           0.250000               0.658537      9.000000
Jake Delhomme       2007                 55        18.333333            86     28.666667              617.0         205.666667                8         2.666667                1.0           0.333333               0.639535      8.000000
Aaron Rodgers       2011                342        22.800000           501     33.400000             4636.0         309.066667               45         3.000000                6.0           0.400000               0.682635      7.500000
Tom Brady           2007                398        24.875000           578     36.125000             4806.0         300.375000               50         3.125000                8.0           0.500000               0.688581      6.250000
David Garrard       2007                208        17.333333           325     27.083333             2509.0         209.083333               18         1.500000                3.0           0.250000               0.640000      6.000000
Matthew Stafford    2010                 57        14.250000            96     24.000000              535.0         133.750000                6         1.500000                1.0           0.250000               0.593750      6.000000
Jeff Garcia         2006                116        14.500000           188     23.500000             1309.0         163.625000               10         1.250000                2.0           0.250000               0.617021      5.000000
Brett Favre         2009                364        22.750000           532     33.250000             4202.0         262.625000               33         2.062500                7.0           0.437500               0.684211      4.714286
Tarvaris Jackson    2008                 88        12.571429           149     21.285714             1056.0         150.857143                9         1.285714                2.0           0.285714               0.590604      4.500000
Aaron Rodgers       2009                350        21.875000           541     33.812500             4434.0         277.125000               30         1.875000                7.0           0.437500               0.646950      4.285714
Josh Freeman        2010                291        18.187500           474     29.625000             3451.0         215.687500               25         1.562500                6.0           0.375000               0.613924      4.166667
David Garrard       2005                 98        14.000000           168     24.000000             1117.0         159.571429                4         0.571429                1.0           0.142857               0.583333      4.000000
Matt Moore          2009                 85        12.142857           138     19.714286             1053.0         150.428571                8         1.142857                2.0           0.285714               0.615942      4.000000
Matt Cassel         2010                262        17.466667           450     30.000000             3116.0         207.733333               27         1.800000                7.0           0.466667               0.582222      3.857143
Seneca Wallace      2008                141        15.666667           242     26.888889             1532.0         170.222222               11         1.222222                3.0           0.333333               0.582645      3.666667
Mike Vick           2010                233        19.416667           372     31.000000             3018.0         251.500000               21         1.750000                6.0           0.500000               0.626344      3.500000
Peyton Manning      2006                362        22.625000           557     34.812500             4397.0         274.812500               31         1.937500                9.0           0.562500               0.649910      3.444444
Ben Roethlisberger  2010                240        20.000000           389     32.416667             3200.0         266.666667               17         1.416667                5.0           0.416667               0.616967      3.400000
Alex Smith          2011                273        17.062500           445     27.812500             3144.0         196.500000               17         1.062500                5.0           0.312500               0.613483      3.400000
Vince Young         2010                 93        10.333333           156     17.333333             1255.0         139.444444               10         1.111111                3.0           0.333333               0.596154      3.333333
Drew Brees          2011                471        29.437500           660     41.250000             5535.0         345.937500               46         2.875000               14.0           0.875000               0.713636      3.285714
Jeff Garcia         2007                209        16.076923           327     25.153846             2440.0         187.692308               13         1.000000                4.0           0.307692               0.639144      3.250000
Tom Brady           2011                401        25.062500           611     38.187500             5235.0         327.187500               39         2.437500               12.0           0.750000               0.656301      3.250000
Philip Rivers       2009                317        19.812500           486     30.375000             4254.0         265.875000               28         1.750000                9.0           0.562500               0.652263      3.111111
Matt Ryan           2010                357        22.312500           571     35.687500             3705.0         231.562500               28         1.750000                9.0           0.562500               0.625219      3.111111
Tony Romo           2011                346        21.625000           522     32.625000             4184.0         261.500000               31         1.937500               10.0           0.625000               0.662835      3.100000
Philip Rivers       2008                312        19.500000           478     29.875000             4004.0         250.250000               34         2.125000               11.0           0.687500               0.652720      3.090909
Drew Brees          2009                363        24.200000           514     34.266667             4388.0         292.533333               34         2.266667               11.0           0.733333               0.706226      3.090909
Jim Sorgi           2005                 43         8.600000            62     12.400000              444.0          88.800000                3         0.600000                1.0           0.200000               0.693548      3.000000
Byron Leftwich      2005                175        15.909091           302     27.454545             2123.0         193.000000               15         1.363636                5.0           0.454545               0.579470      3.000000
Brad Johnson        2005                183        16.636364           293     26.636364             1885.0         171.363636               12         1.090909                4.0           0.363636               0.624573      3.000000
Marc Bulger         2006                370        23.125000           588     36.750000             4301.0         268.812500               24         1.500000                8.0           0.500000               0.629252      3.000000
Donovan McNabb      2006                180        18.000000           316     31.600000             2612.0         261.200000               18         1.800000                6.0           0.600000               0.569620      3.000000
Ben Roethlisberger  2007                265        17.666667           405     27.000000             3158.0         210.533333               32         2.133333               11.0           0.733333               0.654321      2.909091
Tony Romo           2009                347        21.687500           550     34.375000             4483.0         280.187500               26         1.625000                9.0           0.562500               0.630909      2.888889
Donovan McNabb      2007                291        20.785714           473     33.785714             3324.0         237.428571               20         1.428571                7.0           0.500000               0.615222      2.857143
Peyton Manning      2005                305        19.062500           453     28.312500             3747.0         234.187500               28         1.750000               10.0           0.625000               0.673289      2.800000
Chad Pennington     2008                321        20.062500           476     29.750000             3653.0         228.312500               19         1.187500                7.0           0.437500               0.674370      2.714286
Carson Palmer       2005                345        21.562500           509     31.812500             3836.0         239.750000               32         2.000000               12.0           0.750000               0.677800      2.666667

### Spark SQL

In this section I use Spark SQL commands to look at the NFL data.  I start by reading in the file.

In [36]:
# Read in the .csv file with pySpark
nfl_sql=spark.read.csv("data/weekly_nfl_data.csv",header=True, inferSchema=True)

- Here are the first 5 rows

In [37]:
# looking at first 5 rows
nfl_sql.show(5)

+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
| player_id|player_name| player_display_name|position|position_group|headshot_url|recent_team|season|week|season_type|opponent_team|completions|attempts|passing_yards|passing_tds|interceptions|sacks|sack_yards|sack_fumbles|sack_fumbles_lost|passing_air_yards|passing_yards_after_catch|passing_first_downs|passing_epa|passing_2pt_conversions|pacr|dakota|carries|rushing_yards|rushing_tds|rushing_fumbles|rushing_fumbles_lost|rushing_first_downs|rushing_epa|rushing_2pt_conversions|receptions|targets|receiving_yards|receiving_tds|receiving_fumbles|receiving_fumbles_lost|receiving_air_yards|receiving_yards_after_catch|receiving_first_downs|receiving_epa|receiving_2pt_conversions|racr|target_share|air_yards_share|wopr|special_teams_tds|fantasy_points|fantasy_points_ppr|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   1|        REG|          DEN|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     16|         60.0|          1|            0.0|                 0.0|                4.0|   6.248771|                      0|         1|      1|            7.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|   0.29237816|                        0| 0.0|  0.05263158|           NULL|NULL|              0.0|          12.7|              13.7|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   2|        REG|          ARI|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      9|         33.0|          0|            0.0|                 0.0|                1.0| -1.4349501|                      0|         3|      4|           18.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  1.0|    0.3770089|                        0| 0.0|  0.11764706|           NULL|NULL|              0.0|           5.1|               8.1|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        MIA|  1999|   4|        REG|          BUF|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      3|          2.0|          0|            0.0|                 0.0|                0.0| -1.5399517|                      0|         0|      1|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.69957775|                        0|NULL| 0.023809524|           NULL|NULL|              0.0|           0.2|               0.2|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   7|        REG|           LA|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|      6|         27.0|          0|            0.0|                 0.0|                0.0|  0.2160509|                      0|         2|      2|            8.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|  -0.22845396|                        0| 0.0|        0.05|           NULL|NULL|              0.0|           3.5|               5.5|
|00-0000003|       NULL|Abdul-Karim al-Ja...|      RB|            RB|        NULL|        CLE|  1999|   8|        REG|           NO|          0|       0|          0.0|          0|          0.0|  0.0|       0.0|           0|                0|              0.0|                      0.0|                0.0|       NULL|                      0|NULL|  NULL|     13|         39.0|          0|            0.0|                 0.0|                2.0| -2.9722588|                      0|         0|      0|            0.0|            0|              0.0|                   0.0|                0.0|                        0.0|                  0.0|         NULL|                        0|NULL|        NULL|           NULL|NULL|              0.0|           3.9|               3.9|
+----------+-----------+--------------------+--------+--------------+------------+-----------+------+----+-----------+-------------+-----------+--------+-------------+-----------+-------------+-----+----------+------------+-----------------+-----------------+-------------------------+-------------------+-----------+-----------------------+----+------+-------+-------------+-----------+---------------+--------------------+-------------------+-----------+-----------------------+----------+-------+---------------+-------------+-----------------+----------------------+-------------------+---------------------------+---------------------+-------------+-------------------------+----+------------+---------------+----+-----------------+--------------+------------------+
only showing top 5 rows

- Here are all the column names.

In [38]:
# view the columns in nfl data
nfl_sql.columns

['player_id',
 'player_name',
 'player_display_name',
 'position',
 'position_group',
 'headshot_url',
 'recent_team',
 'season',
 'week',
 'season_type',
 'opponent_team',
 'completions',
 'attempts',
 'passing_yards',
 'passing_tds',
 'interceptions',
 'sacks',
 'sack_yards',
 'sack_fumbles',
 'sack_fumbles_lost',
 'passing_air_yards',
 'passing_yards_after_catch',
 'passing_first_downs',
 'passing_epa',
 'passing_2pt_conversions',
 'pacr',
 'dakota',
 'carries',
 'rushing_yards',
 'rushing_tds',
 'rushing_fumbles',
 'rushing_fumbles_lost',
 'rushing_first_downs',
 'rushing_epa',
 'rushing_2pt_conversions',
 'receptions',
 'targets',
 'receiving_yards',
 'receiving_tds',
 'receiving_fumbles',
 'receiving_fumbles_lost',
 'receiving_air_yards',
 'receiving_yards_after_catch',
 'receiving_first_downs',
 'receiving_epa',
 'receiving_2pt_conversions',
 'racr',
 'target_share',
 'air_yards_share',
 'wopr',
 'special_teams_tds',
 'fantasy_points',
 'fantasy_points_ppr']

- Below are quarterback statistics for the regular season from seasons 2005 to 2023. I'm only including the following columns (excluded week):

    player_display_name, season, completions, attempts, passing_yards, passing_tds, and interceptions

In [39]:
#filtering on 2005-2023 regular season qb's
nfl_qb_sql = nfl_sql.filter(
    (nfl_sql["season"] >= 2005) & 
    (nfl_sql["season"] <= 2023) & 
    (nfl_sql["position"] == "QB") & 
    (nfl_sql["season_type"] == "REG")).select(
    "player_display_name", "season", "completions", 
    "attempts", "passing_yards", "passing_tds", "interceptions")
   

nfl_qb_sql.show(5)

+-------------------+------+-----------+--------+-------------+-----------+-------------+
|player_display_name|season|completions|attempts|passing_yards|passing_tds|interceptions|
+-------------------+------+-----------+--------+-------------+-----------+-------------+
|         Tony Banks|  2005|         14|      25|        173.0|          1|          2.0|
|      Charlie Batch|  2005|          9|      16|         65.0|          0|          1.0|
|      Charlie Batch|  2005|         13|      19|        150.0|          0|          0.0|
|      Charlie Batch|  2005|          1|       1|         31.0|          1|          0.0|
|         Jeff Blake|  2005|          1|       1|         11.0|          0|          0.0|
+-------------------+------+-----------+--------+-------------+-----------+-------------+
only showing top 5 rows

- For each player_display_name and season combination, I found the sum and mean of each of the statistical quantities included above. I had to round the mean because it saved many decimal places.

In [40]:
# aggregating stats
nfl_qb_agg= nfl_qb_sql.groupBy(["player_display_name", "season"]).agg(
     F.sum("completions"),F.round(F.mean("completions"), 2),
     F.sum("attempts"),F.round(F.mean("attempts"), 2),
     F.sum("passing_yards"),F.round(F.mean("passing_yards"), 2),
     F.sum("passing_tds"),F.round(F.mean("passing_tds"),2),
     F.sum("interceptions"),F.round(F.mean("interceptions"),2))
     
nfl_qb_agg.show(5)

+-------------------+------+----------------+--------------------------+-------------+-----------------------+------------------+----------------------------+----------------+--------------------------+------------------+----------------------------+
|player_display_name|season|sum(completions)|round(avg(completions), 2)|sum(attempts)|round(avg(attempts), 2)|sum(passing_yards)|round(avg(passing_yards), 2)|sum(passing_tds)|round(avg(passing_tds), 2)|sum(interceptions)|round(avg(interceptions), 2)|
+-------------------+------+----------------+--------------------------+-------------+-----------------------+------------------+----------------------------+----------------+--------------------------+------------------+----------------------------+
|      Jake Delhomme|  2006|             263|                     20.23|          431|                  33.15|            2805.0|                      215.77|              17|                      1.31|              11.0|                        0.85|
|       Jake Plummer|  2005|             277|                     17.31|          456|                   28.5|            3366.0|                      210.38|              18|                      1.13|               7.0|                        0.44|
|        Matt Schaub|  2006|              18|                       3.6|           27|                    5.4|             208.0|                        41.6|               1|                       0.2|               2.0|                         0.4|
|        Vince Young|  2006|             184|                     12.27|          356|                  23.73|            2199.0|                       146.6|              12|                       0.8|              13.0|                        0.87|
|      Kerry Collins|  2007|              50|                      8.33|           82|                  13.67|             531.0|                        88.5|               0|                       0.0|               0.0|                         0.0|
+-------------------+------+----------------+--------------------------+-------------+-----------------------+------------------+----------------------------+----------------+--------------------------+------------------+----------------------------+
only showing top 5 rows

- My column names have gotten long so I'm going to rename them.

In [41]:
# renaming column summaries. 

# desired column names
c = ["player", "season", "sum_completions", "avg_completions", "sum_attempts", "avg_attempts", "sum_passing_yds", 
     "avg_passing_yds", "sum_passing_tds", "avg_passing_tds","sum_interceptions", "avg_interceptions"]

# loop through columns to rename
nfl_qb_stats=nfl_qb_agg
for i, col in enumerate(nfl_qb_agg.columns):
    nfl_qb_stats = nfl_qb_stats.withColumnRenamed(nfl_qb_stats.columns[i], c[i])

nfl_qb_stats.show(10)

+-------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+
|       player|season|sum_completions|avg_completions|sum_attempts|avg_attempts|sum_passing_yds|avg_passing_yds|sum_passing_tds|avg_passing_tds|sum_interceptions|avg_interceptions|
+-------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+
|Jake Delhomme|  2006|            263|          20.23|         431|       33.15|         2805.0|         215.77|             17|           1.31|             11.0|             0.85|
| Jake Plummer|  2005|            277|          17.31|         456|        28.5|         3366.0|         210.38|             18|           1.13|              7.0|             0.44|
|  Matt Schaub|  2006|             18|            3.6|          27|         5.4|          208.0|           41.6|              1|            0.2|              2.0|              0.4|
|  Vince Young|  2006|            184|          12.27|         356|       23.73|         2199.0|          146.6|             12|            0.8|             13.0|             0.87|
|Kerry Collins|  2007|             50|           8.33|          82|       13.67|          531.0|           88.5|              0|            0.0|              0.0|              0.0|
| Todd Collins|  2005|              0|            0.0|           0|         0.0|            0.0|            0.0|              0|            0.0|              0.0|              0.0|
|Charlie Batch|  2006|             30|           4.29|          52|        7.43|          477.0|          68.14|              5|           0.71|              0.0|              0.0|
|  Eli Manning|  2006|            301|          18.81|         522|       32.63|         3244.0|         202.75|             25|           1.56|             18.0|             1.13|
|  A.J. Feeley|  2006|             26|           13.0|          38|        19.0|          342.0|          171.0|              3|            1.5|              0.0|              0.0|
| Mark Brunell|  2006|            162|           16.2|         261|        26.1|         1789.0|          178.9|              8|            0.8|              4.0|              0.4|
+-------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+
only showing top 10 rows

- Now I'm creating two new variables (by season/player combination):

        completion_percentage = (sum of completions)/(sum of attempts)
    
        td_int_ratio = (sum passing tds)/(sum interceptions)

In [42]:
#adding a completion percentage column
nfl_qb_stats1 = nfl_qb_stats.withColumn("completion_percentage",F.round(F.col("sum_completions")/F.col("sum_attempts"), 4))

#adding a touchdown to interception ratio
nfl_qb_stats2=nfl_qb_stats1.withColumn("td_int_ratio", F.round(F.col("sum_passing_tds")/F.col("sum_interceptions"),4))

nfl_qb_stats2.show(10)

+-------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
|       player|season|sum_completions|avg_completions|sum_attempts|avg_attempts|sum_passing_yds|avg_passing_yds|sum_passing_tds|avg_passing_tds|sum_interceptions|avg_interceptions|completion_percentage|td_int_ratio|
+-------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
|Jake Delhomme|  2006|            263|          20.23|         431|       33.15|         2805.0|         215.77|             17|           1.31|             11.0|             0.85|               0.6102|      1.5455|
| Jake Plummer|  2005|            277|          17.31|         456|        28.5|         3366.0|         210.38|             18|           1.13|              7.0|             0.44|               0.6075|      2.5714|
|  Matt Schaub|  2006|             18|            3.6|          27|         5.4|          208.0|           41.6|              1|            0.2|              2.0|              0.4|               0.6667|         0.5|
|  Vince Young|  2006|            184|          12.27|         356|       23.73|         2199.0|          146.6|             12|            0.8|             13.0|             0.87|               0.5169|      0.9231|
|Kerry Collins|  2007|             50|           8.33|          82|       13.67|          531.0|           88.5|              0|            0.0|              0.0|              0.0|               0.6098|        NULL|
| Todd Collins|  2005|              0|            0.0|           0|         0.0|            0.0|            0.0|              0|            0.0|              0.0|              0.0|                 NULL|        NULL|
|Charlie Batch|  2006|             30|           4.29|          52|        7.43|          477.0|          68.14|              5|           0.71|              0.0|              0.0|               0.5769|        NULL|
|  Eli Manning|  2006|            301|          18.81|         522|       32.63|         3244.0|         202.75|             25|           1.56|             18.0|             1.13|               0.5766|      1.3889|
|  A.J. Feeley|  2006|             26|           13.0|          38|        19.0|          342.0|          171.0|              3|            1.5|              0.0|              0.0|               0.6842|        NULL|
| Mark Brunell|  2006|            162|           16.2|         261|        26.1|         1789.0|          178.9|              8|            0.8|              4.0|              0.4|               0.6207|         2.0|
+-------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
only showing top 10 rows

**It's important to note that we did not  need to worry about dividing by 0 in these cases.  Spark SQL automatically assigns those values "NULL".**

- Below I've filtered the rows to only include the player-season combinations where the attempts are >50. Then I've sorted the rows in descending order by completion_percentage and reported the first 40 values.

In [43]:
# filtering on attempts >50 and sorting by completion percentage in descending order
nfl_qb_best = nfl_qb_stats2.filter(F.col("sum_attempts") > 50).orderBy("completion_percentage", ascending=False)

nfl_qb_best.show(40)

+------------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
|            player|season|sum_completions|avg_completions|sum_attempts|avg_attempts|sum_passing_yds|avg_passing_yds|sum_passing_tds|avg_passing_tds|sum_interceptions|avg_interceptions|completion_percentage|td_int_ratio|
+------------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
|        Drew Brees|  2011|            471|          29.44|         660|       41.25|         5535.0|         345.94|             46|           2.88|             14.0|             0.88|               0.7136|      3.2857|
|        Drew Brees|  2009|            363|           24.2|         514|       34.27|         4388.0|         292.53|             34|           2.27|             11.0|             0.73|               0.7062|      3.0909|
|      Jamie Martin|  2005|            124|           15.5|         177|       22.13|         1277.0|         159.63|              5|           0.63|              7.0|             0.88|               0.7006|      0.7143|
|         Tony Romo|  2010|            148|          24.67|         213|        35.5|         1605.0|          267.5|             11|           1.83|              7.0|             1.17|               0.6948|      1.5714|
|         Jim Sorgi|  2005|             43|            8.6|          62|        12.4|          444.0|           88.8|              3|            0.6|              1.0|              0.2|               0.6935|         3.0|
|   Chad Pennington|  2009|             51|           17.0|          74|       24.67|          413.0|         137.67|              1|           0.33|              2.0|             0.67|               0.6892|         0.5|
|         Tom Brady|  2007|            398|          24.88|         578|       36.13|         4806.0|         300.38|             50|           3.13|              8.0|              0.5|               0.6886|        6.25|
|   Chad Pennington|  2007|            179|          19.89|         260|       28.89|         1766.0|         196.22|             10|           1.11|              9.0|              1.0|               0.6885|      1.1111|
|    Peyton Manning|  2009|            393|          24.56|         571|       35.69|         4500.0|         281.25|             33|           2.06|             16.0|              1.0|               0.6883|      2.0625|
|       Brett Favre|  2009|            364|          22.75|         532|       33.25|         4202.0|         262.63|             33|           2.06|              7.0|             0.44|               0.6842|      4.7143|
|        David Carr|  2006|            302|          18.88|         442|       27.63|         2765.0|         172.81|             11|           0.69|             12.0|             0.75|               0.6833|      0.9167|
|     Aaron Rodgers|  2011|            342|           22.8|         501|        33.4|         4636.0|         309.07|             45|            3.0|              6.0|              0.4|               0.6826|         7.5|
|        Drew Brees|  2010|            448|           28.0|         658|       41.13|         4620.0|         288.75|             33|           2.06|             22.0|             1.38|               0.6809|         1.5|
|       Matt Schaub|  2009|            396|          24.75|         583|       36.44|         4770.0|         298.13|             29|           1.81|             15.0|             0.94|               0.6792|      1.9333|
|     Carson Palmer|  2005|            345|          21.56|         509|       31.81|         3836.0|         239.75|             32|            2.0|             12.0|             0.75|               0.6778|      2.6667|
|        Drew Brees|  2007|            443|          27.69|         655|       40.94|         4428.0|         276.75|             28|           1.75|             18.0|             1.13|               0.6763|      1.5556|
|       Luke McCown|  2007|             94|           18.8|         139|        27.8|         1009.0|          201.8|              5|            1.0|              3.0|              0.6|               0.6763|      1.6667|
|        Shaun Hill|  2007|             54|           18.0|          80|       26.67|          501.0|          167.0|              5|           1.67|              2.0|             0.67|                0.675|         2.5|
|   Chad Pennington|  2008|            321|          20.06|         476|       29.75|         3653.0|         228.31|             19|           1.19|              7.0|             0.44|               0.6744|      2.7143|
|     Kelly Holcomb|  2005|            155|           15.5|         230|        23.0|         1509.0|          150.9|             10|            1.0|              8.0|              0.8|               0.6739|        1.25|
|    Peyton Manning|  2005|            305|          19.06|         453|       28.31|         3747.0|         234.19|             28|           1.75|             10.0|             0.63|               0.6733|         2.8|
|       Kurt Warner|  2008|            402|          25.13|         599|       37.44|         4582.0|         286.38|             30|           1.88|             14.0|             0.88|               0.6711|      2.1429|
|       Marc Bulger|  2005|            192|           24.0|         287|       35.88|         2297.0|         287.13|             14|           1.75|              9.0|             1.13|                0.669|      1.5556|
|    Peyton Manning|  2008|            371|          23.19|         555|       34.69|         4002.0|         250.13|             27|           1.69|             12.0|             0.75|               0.6685|        2.25|
|    Sage Rosenfels|  2008|            116|          19.33|         174|        29.0|         1431.0|          238.5|              6|            1.0|             10.0|             1.67|               0.6667|         0.6|
|Ben Roethlisberger|  2009|            337|          22.47|         506|       33.73|         4328.0|         288.53|             26|           1.73|             12.0|              0.8|                0.666|      2.1667|
|       Brett Favre|  2007|            356|          22.25|         535|       33.44|         4157.0|         259.81|             28|           1.75|             15.0|             0.94|               0.6654|      1.8667|
|       Matt Schaub|  2007|            192|          17.45|         289|       26.27|         2241.0|         203.73|              9|           0.82|              9.0|             0.82|               0.6644|         1.0|
|         Tony Romo|  2011|            346|          21.63|         522|       32.63|         4184.0|          261.5|             31|           1.94|             10.0|             0.63|               0.6628|         3.1|
|    Peyton Manning|  2010|            450|          28.13|         679|       42.44|         4700.0|         293.75|             33|           2.06|             17.0|             1.06|               0.6627|      1.9412|
|      Matt Leinart|  2009|             51|           6.38|          77|        9.63|          435.0|          54.38|              0|            0.0|              3.0|             0.38|               0.6623|         0.0|
|       Kurt Warner|  2009|            340|          22.67|         514|       34.27|         3758.0|         250.53|             27|            1.8|             14.0|             0.93|               0.6615|      1.9286|
|       Matt Schaub|  2008|            251|          22.82|         380|       34.55|         3043.0|         276.64|             15|           1.36|             10.0|             0.91|               0.6605|         1.5|
|     Philip Rivers|  2010|            357|          22.31|         541|       33.81|         4710.0|         294.38|             30|           1.88|             13.0|             0.81|               0.6599|      2.3077|
|         Tom Brady|  2010|            324|          20.25|         492|       30.75|         3900.0|         243.75|             36|           2.25|              4.0|             0.25|               0.6585|         9.0|
|         Jon Kitna|  2010|            209|           20.9|         318|        31.8|         2365.0|          236.5|             16|            1.6|             12.0|              1.2|               0.6572|      1.3333|
|       Brett Favre|  2008|            343|          21.44|         522|       32.63|         3472.0|          217.0|             22|           1.38|             22.0|             1.38|               0.6571|         1.0|
|     Aaron Rodgers|  2010|            312|           20.8|         475|       31.67|         3922.0|         261.47|             28|           1.87|             11.0|             0.73|               0.6568|      2.5455|
|         Tom Brady|  2009|            371|          23.19|         565|       35.31|         4398.0|         274.88|             28|           1.75|             13.0|             0.81|               0.6566|      2.1538|
|         Tom Brady|  2011|            401|          25.06|         611|       38.19|         5235.0|         327.19|             39|           2.44|             12.0|             0.75|               0.6563|        3.25|
+------------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
only showing top 40 rows

- Below I've used the dataframe where the player-season combinations where the attempts are >50. Then I've sorted the rows in descending order by td_int_ratio and reported the first 40 values. **I did not have to drop NaN values like in pandas-on-Spark.**

In [44]:
# sorting by td_int_ratio percentage in descending order
nfl_qb_best2 = nfl_qb_best.orderBy("td_int_ratio", ascending=False)

nfl_qb_best2.show(40)

+------------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
|            player|season|sum_completions|avg_completions|sum_attempts|avg_attempts|sum_passing_yds|avg_passing_yds|sum_passing_tds|avg_passing_tds|sum_interceptions|avg_interceptions|completion_percentage|td_int_ratio|
+------------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
|       Damon Huard|  2006|            148|           14.8|         244|        24.4|         1878.0|          187.8|             11|            1.1|              1.0|              0.1|               0.6066|        11.0|
|         Tom Brady|  2010|            324|          20.25|         492|       30.75|         3900.0|         243.75|             36|           2.25|              4.0|             0.25|               0.6585|         9.0|
|     Jake Delhomme|  2007|             55|          18.33|          86|       28.67|          617.0|         205.67|              8|           2.67|              1.0|             0.33|               0.6395|         8.0|
|     Aaron Rodgers|  2011|            342|           22.8|         501|        33.4|         4636.0|         309.07|             45|            3.0|              6.0|              0.4|               0.6826|         7.5|
|         Tom Brady|  2007|            398|          24.88|         578|       36.13|         4806.0|         300.38|             50|           3.13|              8.0|              0.5|               0.6886|        6.25|
|     David Garrard|  2007|            208|          17.33|         325|       27.08|         2509.0|         209.08|             18|            1.5|              3.0|             0.25|                 0.64|         6.0|
|  Matthew Stafford|  2010|             57|          14.25|          96|        24.0|          535.0|         133.75|              6|            1.5|              1.0|             0.25|               0.5938|         6.0|
|       Jeff Garcia|  2006|            116|           14.5|         188|        23.5|         1309.0|         163.63|             10|           1.25|              2.0|             0.25|                0.617|         5.0|
|       Brett Favre|  2009|            364|          22.75|         532|       33.25|         4202.0|         262.63|             33|           2.06|              7.0|             0.44|               0.6842|      4.7143|
|  Tarvaris Jackson|  2008|             88|          12.57|         149|       21.29|         1056.0|         150.86|              9|           1.29|              2.0|             0.29|               0.5906|         4.5|
|     Aaron Rodgers|  2009|            350|          21.88|         541|       33.81|         4434.0|         277.13|             30|           1.88|              7.0|             0.44|                0.647|      4.2857|
|      Josh Freeman|  2010|            291|          18.19|         474|       29.63|         3451.0|         215.69|             25|           1.56|              6.0|             0.38|               0.6139|      4.1667|
|     David Garrard|  2005|             98|           14.0|         168|        24.0|         1117.0|         159.57|              4|           0.57|              1.0|             0.14|               0.5833|         4.0|
|        Matt Moore|  2009|             85|          12.14|         138|       19.71|         1053.0|         150.43|              8|           1.14|              2.0|             0.29|               0.6159|         4.0|
|       Matt Cassel|  2010|            262|          17.47|         450|        30.0|         3116.0|         207.73|             27|            1.8|              7.0|             0.47|               0.5822|      3.8571|
|    Seneca Wallace|  2008|            141|          15.67|         242|       26.89|         1532.0|         170.22|             11|           1.22|              3.0|             0.33|               0.5826|      3.6667|
|         Mike Vick|  2010|            233|          19.42|         372|        31.0|         3018.0|          251.5|             21|           1.75|              6.0|              0.5|               0.6263|         3.5|
|    Peyton Manning|  2006|            362|          22.63|         557|       34.81|         4397.0|         274.81|             31|           1.94|              9.0|             0.56|               0.6499|      3.4444|
|Ben Roethlisberger|  2010|            240|           20.0|         389|       32.42|         3200.0|         266.67|             17|           1.42|              5.0|             0.42|                0.617|         3.4|
|        Alex Smith|  2011|            273|          17.06|         445|       27.81|         3144.0|          196.5|             17|           1.06|              5.0|             0.31|               0.6135|         3.4|
|       Vince Young|  2010|             93|          10.33|         156|       17.33|         1255.0|         139.44|             10|           1.11|              3.0|             0.33|               0.5962|      3.3333|
|        Drew Brees|  2011|            471|          29.44|         660|       41.25|         5535.0|         345.94|             46|           2.88|             14.0|             0.88|               0.7136|      3.2857|
|       Jeff Garcia|  2007|            209|          16.08|         327|       25.15|         2440.0|         187.69|             13|            1.0|              4.0|             0.31|               0.6391|        3.25|
|         Tom Brady|  2011|            401|          25.06|         611|       38.19|         5235.0|         327.19|             39|           2.44|             12.0|             0.75|               0.6563|        3.25|
|     Philip Rivers|  2009|            317|          19.81|         486|       30.38|         4254.0|         265.88|             28|           1.75|              9.0|             0.56|               0.6523|      3.1111|
|         Matt Ryan|  2010|            357|          22.31|         571|       35.69|         3705.0|         231.56|             28|           1.75|              9.0|             0.56|               0.6252|      3.1111|
|         Tony Romo|  2011|            346|          21.63|         522|       32.63|         4184.0|          261.5|             31|           1.94|             10.0|             0.63|               0.6628|         3.1|
|        Drew Brees|  2009|            363|           24.2|         514|       34.27|         4388.0|         292.53|             34|           2.27|             11.0|             0.73|               0.7062|      3.0909|
|     Philip Rivers|  2008|            312|           19.5|         478|       29.88|         4004.0|         250.25|             34|           2.13|             11.0|             0.69|               0.6527|      3.0909|
|         Jim Sorgi|  2005|             43|            8.6|          62|        12.4|          444.0|           88.8|              3|            0.6|              1.0|              0.2|               0.6935|         3.0|
|    Byron Leftwich|  2005|            175|          15.91|         302|       27.45|         2123.0|          193.0|             15|           1.36|              5.0|             0.45|               0.5795|         3.0|
|      Brad Johnson|  2005|            183|          16.64|         293|       26.64|         1885.0|         171.36|             12|           1.09|              4.0|             0.36|               0.6246|         3.0|
|       Marc Bulger|  2006|            370|          23.13|         588|       36.75|         4301.0|         268.81|             24|            1.5|              8.0|              0.5|               0.6293|         3.0|
|    Donovan McNabb|  2006|            180|           18.0|         316|        31.6|         2612.0|          261.2|             18|            1.8|              6.0|              0.6|               0.5696|         3.0|
|Ben Roethlisberger|  2007|            265|          17.67|         405|        27.0|         3158.0|         210.53|             32|           2.13|             11.0|             0.73|               0.6543|      2.9091|
|         Tony Romo|  2009|            347|          21.69|         550|       34.38|         4483.0|         280.19|             26|           1.63|              9.0|             0.56|               0.6309|      2.8889|
|    Donovan McNabb|  2007|            291|          20.79|         473|       33.79|         3324.0|         237.43|             20|           1.43|              7.0|              0.5|               0.6152|      2.8571|
|    Peyton Manning|  2005|            305|          19.06|         453|       28.31|         3747.0|         234.19|             28|           1.75|             10.0|             0.63|               0.6733|         2.8|
|   Chad Pennington|  2008|            321|          20.06|         476|       29.75|         3653.0|         228.31|             19|           1.19|              7.0|             0.44|               0.6744|      2.7143|
|     Carson Palmer|  2005|            345|          21.56|         509|       31.81|         3836.0|         239.75|             32|            2.0|             12.0|             0.75|               0.6778|      2.6667|
+------------------+------+---------------+---------------+------------+------------+---------------+---------------+---------------+---------------+-----------------+-----------------+---------------------+------------+
only showing top 40 rows