**Linda Zier**

**ST 554**

**Project 2**

*03/24/2026*


## Introduction

This project has two parts.  In the first part I have created a data quality class in pyspark. This class is a python class that wraps an SQL DataFrame and provides functionality for cleaning and checking data.

In the second part of the project I analyze data using Spark SQL style dataframes and pandas-on-Spark data frames.

## Part I - Creating a Class

I've created a data folder on my github repository and stored the air quality data there.  This part of the project utilizes the air quality data set available at the UCI Machine Learning Repository (https://archive.ics.uci.edu/dataset/360/air+quality). This data is time series data (data recorded over time) for air quality measurements of pollutants in an Italian city. The dataset consists of 9,358 hourly-averaged observations collected from five metal oxide chemical sensors integrated into an air quality multisensor device. The device was deployed at road level in a heavily polluted urban area in Italy, and data were gathered over a one-year period from March 2004 through February 2005 (De Vito, 2008).

The pollutants measured, which are "true" (gold standard) measurements, are the following:

- CO(GT) (CO concentration)
- C6H6(GT) (Benzene concentration)
- NMHC(GT) (Non Metanic HydroCarbon concentration)
- NOx(GT) (NOx concentration)
- NO2(GT) (NO2 concentration)
- T (temperature)
- RH (Relative humidity)
- AH (Absolute Humidity)

In [33]:
# imports 
from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [34]:
# imports to run when the kernel gets restarted

import Spark_class
from Spark_class import SparkDataCheck

import importlib
importlib.reload(Spark_class)

    After loading the data, we check the numeric data types for missing values indicated by an entry of -200. We replace those with None to give NULL values.

In [35]:

# Loading the air data using the from_csv method 
air = Spark_class.SparkDataCheck.from_csv(spark, "data/air.csv")
   
air.df.printSchema(5)

#get numeric columns
numeric_types = ['int', 'bigint', 'float', 'double', 'decimal', 'long', 'short']
#columns_to_clean = [c for c, dtype in air.df.dytpes

#cleaning up : replacing the -200 values with NULL
for c, dtype in air.df.dtypes:
    if dtype in numeric_types:
        air.df=air.df.withColumn(c, F.when(F.col(f'`{c}`')== -200, None).otherwise(F.col(f'`{c}`')))
    
air.df.show(5)

root
 |-- _c0: integer (nullable = true)
 |-- Date: string (nullable = true)
 |-- Time: timestamp (nullable = true)
 |-- CO(GT): double (nullable = true)
 |-- PT08.S1(CO): integer (nullable = true)
 |-- NMHC(GT): integer (nullable = true)
 |-- C6H6(GT): double (nullable = true)
 |-- PT08.S2(NMHC): integer (nullable = true)
 |-- NOx(GT): integer (nullable = true)
 |-- PT08.S3(NOx): integer (nullable = true)
 |-- NO2(GT): integer (nullable = true)
 |-- PT08.S4(NO2): integer (nullable = true)
 |-- PT08.S5(O3): integer (nullable = true)
 |-- T: double (nullable = true)
 |-- RH: double (nullable = true)
 |-- AH: double (nullable = true)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

    In order to test the string methods, I needed to add a few more columns with string variables.  It made sense to quantify temperature and relative humidity. I also needed to ensure the NULL values didn't end up in one of the other categories to falsely record the level.

In [36]:
# making some string columns that hopefully make sense

air.df = air.df.withColumn('T_level',F.when(F.col('T') > 20, 'high').
                           when(F.col('T') > 10, 'medium').when(F.col('T') >= 0, 'low').otherwise(None))

air.df = air.df.withColumn('RH_level',F.when(F.col('RH') > 60,'high').
                           when(F.col('RH')>30, 'medium').when(F.col('RH') >= 0, 'low').otherwise(None))

air.df.show()

#checking to make sure the NULL values don't end up in one of the other categories to falsely record the level
result = air.check_null("RH")
result.df.filter(F.col('null_check') == True).show(5)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
|524|4/1/2004|2026-03-23 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|525|4/1/2004|2026-03-23 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|526|4/1/2004|2026-03-23 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|701|4/8/2004|2026-03-23 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
|702|4/9/2004|2026-03-23 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+
only showing top 5 rows

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

### Validation Method Examples
    Below are several examples of using validation methods with SparkDataCheck

**Checking numeric range**
- Here is an example of using my methods on the air quality data to check if it falls between 2 values.

In [37]:
result=air.check_col_range(column="T", lower=10.0, upper=11.1)
result.df.show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|    false|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|    false|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|    false|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|    false|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|     true|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|     true|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Now I'm showing what happens when you don't have at least a lower or an upper value for the range.

In [38]:
result=air.check_col_range(column="T")
#result.df.show(10)

Need a lower and/or an upper range for T

- Here I've supplied only an upper range in one case and only a lower case in another.

In [39]:
air.check_col_range(column="CO(GT)", upper=2.0)
air.df.show(10)

air.check_col_range(column="NOx(GT)", lower=100)
air.df.show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|    false|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|    false|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|    false|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|     true|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|     true|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|     true|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|     true|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 10 rows

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Here I've tested something that wasn't one of the number types we specified.

In [40]:
air.check_col_range(column="T_level", lower=0)

Column is not numeric

In [41]:
# this was a visual for me to see what types I had to work with.
#air.df.dtypes

**Checking for null values**
- First I am checking for NULL values in the T (temperature) column. I'm also filtering on just Null in that column so it's easy to check.

In [42]:
#air.df.toPandas().isnull().sum()

# check for null in T
result=air.check_null(column="T")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|num_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|524|4/1/2004|2026-03-23 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|525|4/1/2004|2026-03-23 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|526|4/1/2004|2026-03-23 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|701|4/8/2004|2026-03-23 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|702|4/9/2004|2026-03-23 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|703|4/9/2004|2026-03-23 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|704|4/9/2004|2026-03-23 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|705|4/9/2004|2026-03-23 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     NULL|
|706|4/9/2004|2026-03-23 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|707|4/9/2004|2026-03-23 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
only showing top 10 rows

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

In [43]:
# I used this to see counts 
# air.df.toPandas().isnull().sum()

- Below I am checking for NULL values in the RH (relative humidity) column. I also filter on NULL so it's easy to verify.

In [44]:
# check for null in RH
result=air.check_null(column="RH")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

26/03/23 18:03:57 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|num_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|524|4/1/2004|2026-03-23 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|525|4/1/2004|2026-03-23 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|526|4/1/2004|2026-03-23 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|701|4/8/2004|2026-03-23 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|702|4/9/2004|2026-03-23 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|703|4/9/2004|2026-03-23 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|704|4/9/2004|2026-03-23 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|705|4/9/2004|2026-03-23 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     NULL|
|706|4/9/2004|2026-03-23 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|707|4/9/2004|2026-03-23 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
only showing top 10 rows

- Here I'm checking for null values in the date column.  There are no missing values so this was a good way to verify that it was working.

In [45]:
# check for null in Date
result=air.check_null(column="Date")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 20 rows
+---+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+----------+---------+
|_c0|Date|Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|  T| RH| AH|T_level|RH_level|null_check|num_check|
+---+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+----------+---------+
+---+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+----------+---------+

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Here I'm checking for null values in the Benzene concentration(C6H6(GT)) column.

In [46]:
# check for null in C6H6(GT)
result=air.check_null(column="C6H6(GT)")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|null_check|num_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
|524|4/1/2004|2026-03-23 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|525|4/1/2004|2026-03-23 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|526|4/1/2004|2026-03-23 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|701|4/8/2004|2026-03-23 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|702|4/9/2004|2026-03-23 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|703|4/9/2004|2026-03-23 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
|704|4/9/2004|2026-03-23 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|705|4/9/2004|2026-03-23 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     NULL|
|706|4/9/2004|2026-03-23 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|    false|
|707|4/9/2004|2026-03-23 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|      true|     true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+----------+---------+
only showing top 10 rows

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Now I can check if each value in a string column falls within a user specified set of levels and returns the dataframe with an appended column of Boolean values. Below I've checked various string column levels with 4 examples.

In [47]:
print('\n\n Temp level = low')
air.check_string('T_level', 'low')
air.df.show()

print('\n\n RH level = high')
air.check_string('RH_level', 'high')
air.df.show() 

print('\n\n Temp level = medium')
air.check_string('T_level', 'medium')
air.df.show()

# you can see that these values are the same as previous because RH is not a string
air.check_string('RH', 'medium')
air.df.show()

 Temp level = low

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|    false|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|    false|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|    false|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|    false|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|    false|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|    false|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|    false|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|    false|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|    false|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|    false|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|    false|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|    false|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|    false|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|    false|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|     true|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows


 RH level = high

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|    false|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|    false|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|    false|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|    false|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|    false|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|    false|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|    false|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|    false|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|    false|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|     true|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|     true|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|    false|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|    false|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|    false|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|    false|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|    false|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|    false|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|     true|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows


 Temp level = medium
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|     true|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|     true|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|     true|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|     true|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|     true|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|     true|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|     true|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|     true|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|     true|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|     true|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|     true|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|     true|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|    false|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|    false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows
Column is not a string
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|null_check|num_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
|  0|3/10/2004|2026-03-23 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     false|     true|     true|
|  1|3/10/2004|2026-03-23 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     false|     true|     true|
|  2|3/10/2004|2026-03-23 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     false|     true|     true|
|  3|3/10/2004|2026-03-23 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     false|     true|     true|
|  4|3/10/2004|2026-03-23 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     false|     true|     true|
|  5|3/10/2004|2026-03-23 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     false|    false|     true|
|  6|3/11/2004|2026-03-23 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     false|    false|     true|
|  7|3/11/2004|2026-03-23 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     false|    false|     true|
|  8|3/11/2004|2026-03-23 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     false|    false|     true|
|  9|3/11/2004|2026-03-23 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     false|     NULL|     true|
| 10|3/11/2004|2026-03-23 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|     false|    false|     true|
| 11|3/11/2004|2026-03-23 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|     false|    false|     true|
| 12|3/11/2004|2026-03-23 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|     false|    false|     true|
| 13|3/11/2004|2026-03-23 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|     false|    false|     true|
| 14|3/11/2004|2026-03-23 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     false|     true|     true|
| 15|3/11/2004|2026-03-23 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     false|     true|     true|
| 16|3/11/2004|2026-03-23 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     false|     true|     true|
| 17|3/11/2004|2026-03-23 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|     false|    false|     true|
| 18|3/11/2004|2026-03-23 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     false|     true|    false|
| 19|3/11/2004|2026-03-23 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     false|     true|    false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+----------+---------+---------+
only showing top 20 rows

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

### Summarization Method Examples

Below I've given some examples of the summarization methods.

- This summarizes all the numeric columns since no column was entered in the method call.

In [48]:
air.col_minmax()

26/03/23 18:03:58 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

         col_name       min       max
0             _c0    0.0000  9356.000
1          CO(GT)    0.1000    11.900
2     PT08.S1(CO)  647.0000  2040.000
3        NMHC(GT)    7.0000  1189.000
4        C6H6(GT)    0.1000    63.700
5   PT08.S2(NMHC)  383.0000  2214.000
6         NOx(GT)    2.0000  1479.000
7    PT08.S3(NOx)  322.0000  2683.000
8         NO2(GT)    2.0000   340.000
9    PT08.S4(NO2)  551.0000  2775.000
10    PT08.S5(O3)  221.0000  2523.000
11              T   -1.9000    44.600
12             RH    9.2000    88.700
13             AH    0.1847     2.231

- Now I summarize a few diffent numeric columns to show functionality. This includes 2 examples of grouped levels

In [49]:
air.col_minmax("CO(GT)")

  col_name  min   max
0   CO(GT)  0.1  11.9

In [50]:
air.col_minmax("C6H6(GT)", "T_level")

   col_name T_level  min   max
0  C6H6(GT)     low  0.1  63.7
1  C6H6(GT)    None  0.2  12.4
2  C6H6(GT)    high  1.0  52.1
3  C6H6(GT)  medium  0.2  50.8

In [51]:
air.col_minmax("C6H6(GT)", "RH_level")

   col_name RH_level  min   max
0  C6H6(GT)      low  0.9  38.4
1  C6H6(GT)     None  NaN   NaN
2  C6H6(GT)     high  0.5  52.1
3  C6H6(GT)   medium  0.1  63.7

In this case I call a non-numeric column

In [52]:
air.col_minmax("T_level")

Column T_level is not numeric


I will report the counts associated with one or two string columns.
- Below are the temporature counts for each category.

In [53]:
air.str_count('T_level')

  T_level  count
0     low   1683
1    None    379
2    high   3711
3  medium   3584

- Below are the relative humidity counts for each category.

In [54]:
air.str_count('RH_level')

  RH_level  count
0      low   1441
1     None    366
2     high   2633
3   medium   4917

In [55]:
result=air.str_count('T_level', 'RH_level')
result.sort_values(['T_level', 'RH_level'])

   T_level RH_level  count
2     high     high    375
8     high      low   1186
5     high   medium   2150
0      low     high    771
7      low      low     33
10     low   medium    879
4   medium     high   1487
9   medium      low    222
3   medium   medium   1875
6     None   medium     13
1     None     None    366

In [56]:
#result['T_level'] = pd.Categorical(result['T_level'], categories=['low', 'medium', 'high'], ordered=True)
#result['RH_level'] = pd.Categorical(result['RH_level'], categories=['low', 'medium', 'high'], ordered=True)
#result.sort_values(['T_level', 'RH_level'])

Now I'll read that same data set in using pandas.

In [57]:
# read the file from pandas
air_pd=pd.read_csv("data/air.csv")

#convert into SDC object
air2 =Spark_class.SparkDataCheck.from_pd(spark, air_pd)

- Here is one example of a method call; in this case Null check

In [58]:
air2.check_null("T").df.show()

+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+
|Unnamed: 0|     Date|    Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|null_check|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+
|         0|3/10/2004|18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|     false|
|         1|3/10/2004|19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|     false|
|         2|3/10/2004|20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|     false|
|         3|3/10/2004|21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|     false|
|         4|3/10/2004|22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|     false|
|         5|3/10/2004|23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848|     false|
|         6|3/11/2004| 0:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603|     false|
|         7|3/11/2004| 1:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702|     false|
|         8|3/11/2004| 2:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648|     false|
|         9|3/11/2004| 3:00:00|   0.6|       1010|      19|     1.7|          561|   -200|        1705|   -200|        1235|        501|10.3|60.2|0.7517|     false|
|        10|3/11/2004| 4:00:00|-200.0|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465|     false|
|        11|3/11/2004| 5:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366|     false|
|        12|3/11/2004| 6:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353|     false|
|        13|3/11/2004| 7:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417|     false|
|        14|3/11/2004| 8:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408|     false|
|        15|3/11/2004| 9:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691|     false|
|        16|3/11/2004|10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552|     false|
|        17|3/11/2004|11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352|     false|
|        18|3/11/2004|12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|     false|
|        19|3/11/2004|13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|     false|
+----------+---------+--------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+----------+
only showing top 20 rows

## Part II - Spark SQL and pandas-on-Spark APIs

In this section we’re going to do some basic analysis using Spark APIs (Application Programming Interface) on some NFL
data.

### pandas-on-Spark

In this section we use pandas-on-Spark commands to look at NFL data.

In [59]:
# Spark and pandas imports
from pyspark.sql import SparkSession
from pyspark.sql import functions as F
import pyspark.pandas as ps

ps.set_option('compute.fail_on_ansi_mode', False)
import pandas as pd
import numpy as np

# Read in the .csv file
nfl_df=ps.read_csv("data/weekly_nfl_data.csv")

# Look at the first 5 rows
nfl_df.head(5)

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)
/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: If `index_col` is not specified for `read_csv`, the default index is attached which can cause additional overhead.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

    player_id player_name    player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr  dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
0  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     1         REG           DEN            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       16           60.0            1              0.0                   0.0                  4.0     6.248771                        0           1        1              7.0              0                0.0                     0.0                  0.0                          0.0                    0.0       0.292378                          0   0.0      0.052632              NaN   NaN                0.0            12.7                13.7
1  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     2         REG           ARI            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        9           33.0            0              0.0                   0.0                  1.0    -1.434950                        0           3        4             18.0              0                0.0                     0.0                  0.0                          0.0                    1.0       0.377009                          0   0.0      0.117647              NaN   NaN                0.0             5.1                 8.1
2  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         MIA    1999     4         REG           BUF            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        3            2.0            0              0.0                   0.0                  0.0    -1.539952                        0           0        1              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.699578                          0   NaN      0.023810              NaN   NaN                0.0             0.2                 0.2
3  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     7         REG            LA            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN        6           27.0            0              0.0                   0.0                  0.0     0.216051                        0           2        2              8.0              0                0.0                     0.0                  0.0                          0.0                    0.0      -0.228454                          0   0.0      0.050000              NaN   NaN                0.0             3.5                 5.5
4  00-0000003        None  Abdul-Karim al-Jabbar       RB             RB         None         CLE    1999     8         REG            NO            0         0            0.0            0            0.0    0.0         0.0             0                  0                0.0                        0.0                  0.0          NaN                        0   NaN     NaN       13           39.0            0              0.0                   0.0                  2.0    -2.972259                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0             3.9                 3.9

Here we look at the mcolumns in the NFL data so we can make meaningful decisions about what stats interest us.

In [60]:
# look at columns in the nfl data
nfl_df.columns
nfl_df.dtypes

player_id                       object
player_name                     object
player_display_name             object
position                        object
position_group                  object
headshot_url                    object
recent_team                     object
season                           int32
week                             int32
season_type                     object
opponent_team                   object
completions                      int32
attempts                         int32
passing_yards                  float64
passing_tds                      int32
interceptions                  float64
sacks                          float64
sack_yards                     float64
sack_fumbles                     int32
sack_fumbles_lost                int32
passing_air_yards              float64
passing_yards_after_catch      float64
passing_first_downs            float64
passing_epa                    float64
passing_2pt_conversions          int32
pacr                           float64
dakota                         float64
carries                          int32
rushing_yards                  float64
rushing_tds                      int32
rushing_fumbles                float64
rushing_fumbles_lost           float64
rushing_first_downs            float64
rushing_epa                    float64
rushing_2pt_conversions          int32
receptions                       int32
targets                          int32
receiving_yards                float64
receiving_tds                    int32
receiving_fumbles              float64
receiving_fumbles_lost         float64
receiving_air_yards            float64
receiving_yards_after_catch    float64
receiving_first_downs          float64
receiving_epa                  float64
receiving_2pt_conversions        int32
racr                           float64
target_share                   float64
air_yards_share                float64
wopr                           float64
special_teams_tds              float64
fantasy_points                 float64
fantasy_points_ppr             float64
dtype: object

Below we look at quarterback statistics for the regular season from seasons 2005 to 2023.

In [61]:
nfl_seasons_df = nfl_df[(nfl_df["season"] >= 2005) & (nfl_df["season"]<=2023) 
                        & (nfl_df["position"] == "QB")
                        & (nfl_df["season_type"] == "REG")]

nfl_seasons_df.head(5)

/opt/tljh/user/envs/pySpark3/lib/python3.9/site-packages/pyspark/pandas/utils.py:1037: PandasAPIOnSparkAdviceWarning: The config 'spark.sql.ansi.enabled' is set to True. This can cause unexpected behavior from pandas API on Spark since pandas API on Spark follows the behavior of pandas, not SQL.
  warnings.warn(message, PandasAPIOnSparkAdviceWarning)

        player_id player_name player_display_name position position_group headshot_url recent_team  season  week season_type opponent_team  completions  attempts  passing_yards  passing_tds  interceptions  sacks  sack_yards  sack_fumbles  sack_fumbles_lost  passing_air_yards  passing_yards_after_catch  passing_first_downs  passing_epa  passing_2pt_conversions  pacr    dakota  carries  rushing_yards  rushing_tds  rushing_fumbles  rushing_fumbles_lost  rushing_first_downs  rushing_epa  rushing_2pt_conversions  receptions  targets  receiving_yards  receiving_tds  receiving_fumbles  receiving_fumbles_lost  receiving_air_yards  receiving_yards_after_catch  receiving_first_downs  receiving_epa  receiving_2pt_conversions  racr  target_share  air_yards_share  wopr  special_teams_tds  fantasy_points  fantasy_points_ppr
29406  00-0000722        None          Tony Banks       QB             QB         None         HOU    2005    17         REG            SF           14        25          173.0            1            2.0    0.0        -0.0             0                  0                0.0                        0.0                  7.0    -3.693779                        0   0.0  0.032036        2           -2.0            0              0.0                   0.0                  0.0     0.000000                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            6.72                6.72
29426  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005     9         REG            GB            9        16           65.0            0            1.0    1.0         6.0             1                  0                0.0                        0.0                  4.0    -6.609788                        0   0.0  0.025249        8           14.0            0              0.0                   0.0                  1.0    -1.614163                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            2.00                2.00
29427  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005    10         REG           CLE           13        19          150.0            0            0.0    0.0        -0.0             0                  0                0.0                        0.0                  7.0     5.193222                        0   0.0  0.171917        3           16.0            1              0.0                   0.0                  2.0     0.737467                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0           13.60               13.60
29428  00-0000865        None       Charlie Batch       QB             QB         None         PIT    2005    16         REG           CLE            1         1           31.0            1            0.0    0.0        -0.0             0                  0                0.0                        0.0                  1.0     4.662244                        0   0.0       NaN        0            0.0            0              0.0                   0.0                  0.0          NaN                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            5.24                5.24
29447  00-0001335        None          Jeff Blake       QB             QB         None         CHI    2005     2         REG           DET            1         1           11.0            0            0.0    0.0        -0.0             0                  0                0.0                        0.0                  1.0     1.514100                        0   0.0       NaN        1           -1.0            0              0.0                   0.0                  0.0    -2.570310                        0           0        0              0.0              0                0.0                     0.0                  0.0                          0.0                    0.0            NaN                          0   NaN           NaN              NaN   NaN                0.0            0.34                0.34

 - We now look at just the columns that include the player_display_name and some key statistics relevant to quarterbacks: season, week, completions, attempts, passing_yards, passing_tds, and interceptions.

In [62]:
nfl_brief_df = nfl_seasons_df[["player_display_name", "season", "week", "completions",
                               "attempts", "passing_yards", "passing_tds", "interceptions"]]

nfl_brief_df.head(5)

      player_display_name  season  week  completions  attempts  passing_yards  passing_tds  interceptions
29406          Tony Banks    2005    17           14        25          173.0            1            2.0
29426       Charlie Batch    2005     9            9        16           65.0            0            1.0
29427       Charlie Batch    2005    10           13        19          150.0            0            0.0
29428       Charlie Batch    2005    16            1         1           31.0            1            0.0
29447          Jeff Blake    2005     2            1         1           11.0            0            0.0

– For each player_display_name and season combination, we found the sum and mean of each of the
statistical quantities we included above.

In [63]:
result = nfl_brief_df.groupby("player_display_name", "season").agg(
    sum("completions").alias("total_completions"),
    mean("completions").alias("avg_completions"),
    sum("attempts").alias("total_attempts"),
    mean("attempts").alias("avg_attempts"),
    sum("passing_yards").alias("total_passing_yards"),
    mean("passing_yards").alias("avg_passing_yards"),
    sum("passing_tds").alias("total_passing_tds"),
    mean("passing_tds").alias("avg_passing_tds"),
    sum("interceptions").alias("total_interceptions"),
    mean("interceptions").alias("avg_interceptions"))

ValueError: No axis named season

– Create two new variables (by season/player combination):
∗ completion_percentage = (sum of completions)/(sum of attempts)
∗ td_int_ratio = (sum passing tds)/(sum interceptions)