### Linda Zier
### ST 554
### Project 2

**Introduction**

This project has two parts.  In the first part I have created a data quality class in pyspark. This class is a python class that wraps an SQL DataFrame and provides functionality for cleaning and checking data.

In the second part of the project I analyze data using spark SQL style dataframes and pandas-on-spark data frames.

In [161]:

from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from functools import reduce
from pyspark.sql.types import *
import pandas as pd

from pyspark.sql import SparkSession
spark = SparkSession.builder.getOrCreate()

In [162]:
import sys
sys.path.insert(0,'.')

import importlib
import Spark_class
importlib.reload(Spark_class)

from Spark_class import SparkDataCheck

I've created a data folder on my github repository and stored the air quality data there.  This project utilizes the air quality data set available at the UCI Machine Learning Repository (https://archive.ics.uci.edu/dataset/360/air+quality). This data is time series data (data recorded over time) for air quality measurements of pollutants in an Italian city. The dataset consists of 9,358 hourly-averaged observations collected from five metal oxide chemical sensors integrated into an air quality multisensor device. The device was deployed at road level in a heavily polluted urban area in Italy, and data were gathered over a one-year period from March 2004 through February 2005 (De Vito, 2008).

The pollutants measured, which are "true" (gold standard) measurements, are the following:

- CO(GT) (CO concentration)
- C6H6(GT) (Benzene concentration)
- NMHC(GT) (Non Metanic HydroCarbon concentration)
- NOx(GT) (NOx concentration)
- NO2(GT) (NO2 concentration)
- T (temperature)
- RH (Relative humidity)
- AH (Absolute Humidity)

The data has missing values indicated by an entry of -200 so I started by replacing those with None to give NULL values.

In [163]:

# Loading the air data using the from_csv method
air = Spark_class.SparkDataCheck.from_csv(spark, "data/air.csv")
   
air.df.printSchema(5)

#get numeric columns
numeric_types = ['int', 'bigint', 'float', 'double', 'decimal', 'long', 'short']
#columns_to_clean = [c for c, dtype in air.df.dytpes

#cleaning up : replacing the -200 values with NULL
for c, dtype in air.df.dtypes:
    if dtype in numeric_types:
        air.df=air.df.withColumn(c, F.when(F.col(f'`{c}`')== -200, None).otherwise(F.col(f'`{c}`')))
    
air.df.show(5)

root
 |-- _c0: integer (nullable = true)
 |-- Date: string (nullable = true)
 |-- Time: timestamp (nullable = true)
 |-- CO(GT): double (nullable = true)
 |-- PT08.S1(CO): integer (nullable = true)
 |-- NMHC(GT): integer (nullable = true)
 |-- C6H6(GT): double (nullable = true)
 |-- PT08.S2(NMHC): integer (nullable = true)
 |-- NOx(GT): integer (nullable = true)
 |-- PT08.S3(NOx): integer (nullable = true)
 |-- NO2(GT): integer (nullable = true)
 |-- PT08.S4(NO2): integer (nullable = true)
 |-- PT08.S5(O3): integer (nullable = true)
 |-- T: double (nullable = true)
 |-- RH: double (nullable = true)
 |-- AH: double (nullable = true)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+
only showing top 5 rows

26/03/22 21:14:07 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

In order to test the string methods, I needed to add a few more columns with string variables.  It made sense to quantify temperature and relative humidity. I also needed to ensure the NULL values didn't end up in one of the other categories to falsely record the level.

In [184]:
# making some string columns that hopefully make sense

air.df = air.df.withColumn('T_level',F.when(F.col('T') > 20, 'high').
                           when(F.col('T') > 10, 'medium').when(F.col('T') >= 0, 'low').otherwise('NULL'))

air.df = air.df.withColumn('RH_level',F.when(F.col('RH') > 60,'high').
                           when(F.col('RH')>30, 'medium').when(F.col('RH') >= 0, 'low').otherwise('NULL'))

air.df.show()

#checking to make sure the NULL values don't end up in one of the other categories to falsely record the level
result.df.filter(F.col('null_check') == True).show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|     true|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|     true|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|     true|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|     true|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|     true|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|     true|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|     true|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|     true|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|     true|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|     true|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|     true|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|     true|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|     true|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|     true|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|     true|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|     true|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|     true|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|     true|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|    false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|    false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+---------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|num_check|null_check|str_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+---------+
|524|4/1/2004|2026-03-22 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|    false|      true|    false|
|525|4/1/2004|2026-03-22 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     true|      true|    false|
|526|4/1/2004|2026-03-22 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     true|      true|    false|
|701|4/8/2004|2026-03-22 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     true|      true|    false|
|702|4/9/2004|2026-03-22 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     true|      true|    false|
|703|4/9/2004|2026-03-22 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     true|      true|    false|
|704|4/9/2004|2026-03-22 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|    false|      true|    false|
|705|4/9/2004|2026-03-22 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     NULL|      true|    false|
|706|4/9/2004|2026-03-22 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|    false|      true|    false|
|707|4/9/2004|2026-03-22 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|   NULL|    NULL|     true|      true|    false|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+---------+
only showing top 10 rows

26/03/22 21:22:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/22 21:22:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

### Examples

- Here is an example of using my methods on the air quality data to check between 2 values.

In [165]:
result=air.check_col_range(column="T", lower=10.0, upper=11.1)
result.df.show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|    false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|    false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|    false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|    false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     true|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     true|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
only showing top 10 rows

26/03/22 21:14:07 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Now I'm showing what happens when you don't have at least a lower or an upper.

In [166]:
result=air.check_col_range(column="T")
#result.df.show(10)

Need a lower and/or an upper range for T

- Here I've supplied only an upper range in one case and a lower case in another.

In [167]:
air.check_col_range(column="CO(GT)", upper=2.0)
air.df.show(10)

air.check_col_range(column="NOx(GT)", lower=100)
air.df.show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|    false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|    false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|    false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|     true|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|     true|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|     true|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|     true|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
only showing top 10 rows
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+
only showing top 10 rows

26/03/22 21:14:07 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/22 21:14:07 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Here I've tested something that wasn't one of the number types we specified.

In [185]:
air.check_col_range(column="T_level", lower=0)

Column is not numeric

In [186]:
# this was a visual for me to see what types I had to work with.
#air.df.dtypes

**Now I'm going to give some examples of checking for null values**
- First I am checking for NULL values in the T (temperature) column. I'm also filtering on just Null in that column so it's easy to check.

In [170]:
#air.df.toPandas().isnull().sum()

# check for null in T
result=air.check_null(column="T")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|num_check|null_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
|524|4/1/2004|2026-03-22 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|525|4/1/2004|2026-03-22 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|526|4/1/2004|2026-03-22 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|701|4/8/2004|2026-03-22 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|702|4/9/2004|2026-03-22 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|703|4/9/2004|2026-03-22 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|704|4/9/2004|2026-03-22 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|705|4/9/2004|2026-03-22 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     NULL|      true|
|706|4/9/2004|2026-03-22 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|707|4/9/2004|2026-03-22 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
only showing top 10 rows

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

In [171]:
# I used this to see counts 
# air.df.toPandas().isnull().sum()

- Below I am checking for NULL values in the RH (relative humidity) column. I also filter on NULL so it's easy to verify.

In [172]:
# check for null in RH
result=air.check_null(column="RH")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|num_check|null_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
|524|4/1/2004|2026-03-22 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|525|4/1/2004|2026-03-22 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|526|4/1/2004|2026-03-22 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|701|4/8/2004|2026-03-22 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|702|4/9/2004|2026-03-22 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|703|4/9/2004|2026-03-22 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|704|4/9/2004|2026-03-22 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|705|4/9/2004|2026-03-22 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     NULL|      true|
|706|4/9/2004|2026-03-22 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|707|4/9/2004|2026-03-22 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
only showing top 10 rows

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Here I'm checking for null values in the date column.  There are no missing values so this was a good way to verify that it was working.

In [173]:
# check for null in Date
result=air.check_null(column="Date")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
only showing top 20 rows
+---+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+---------+----------+
|_c0|Date|Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|  T| RH| AH|T_level|RH_level|num_check|null_check|
+---+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+---------+----------+
+---+----+----+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+---+---+---+-------+--------+---------+----------+

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Here I'm checking for null values in the Benzene concentration(C6H6(GT)) column.

In [174]:
# check for null in C6H6(GT)
result=air.check_null(column="C6H6(GT)")
result.df.show()

result.df.filter(F.col('null_check') == True).show(10)

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+
only showing top 20 rows
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
|_c0|    Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|  AH|T_level|RH_level|num_check|null_check|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
|524|4/1/2004|2026-03-22 14:00:00|   1.7|       NULL|     222|    NULL|         NULL|     99|        NULL|     72|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|525|4/1/2004|2026-03-22 15:00:00|   1.9|       NULL|     197|    NULL|         NULL|    108|        NULL|     81|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|526|4/1/2004|2026-03-22 16:00:00|   2.3|       NULL|     319|    NULL|         NULL|    131|        NULL|     93|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|701|4/8/2004|2026-03-22 23:00:00|   2.0|       NULL|     137|    NULL|         NULL|    129|        NULL|    106|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|702|4/9/2004|2026-03-22 00:00:00|   2.4|       NULL|     189|    NULL|         NULL|    154|        NULL|    109|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|703|4/9/2004|2026-03-22 01:00:00|   1.8|       NULL|     159|    NULL|         NULL|    118|        NULL|     97|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
|704|4/9/2004|2026-03-22 02:00:00|   1.0|       NULL|      80|    NULL|         NULL|     69|        NULL|     83|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|705|4/9/2004|2026-03-22 03:00:00|   1.0|       NULL|      66|    NULL|         NULL|   NULL|        NULL|   NULL|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     NULL|      true|
|706|4/9/2004|2026-03-22 04:00:00|   1.0|       NULL|      87|    NULL|         NULL|     97|        NULL|     79|        NULL|       NULL|NULL|NULL|NULL|    low|     low|    false|      true|
|707|4/9/2004|2026-03-22 05:00:00|   0.9|       NULL|      79|    NULL|         NULL|    145|        NULL|     84|        NULL|       NULL|NULL|NULL|NULL|    low|     low|     true|      true|
+---+--------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+----+-------+--------+---------+----------+
only showing top 10 rows

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

- Now I can check if each value in a string column falls within a user specified set of levels and returns the dataframe with an appended column of Boolean values. Below I've checked various string column levels.

In [175]:
print('\n\n Temp level = low')
air.check_string('T_level', 'low')
air.df.show()

print('\n\n RH level = high')
air.check_string('RH_level', 'high')
air.df.show() 

print('\n\n Temp level = medium')
air.check_string('T_level', 'medium')
air.df.show()

# you can see that these values are the same as previous because RH is not a string
air.check_string('RH', 'medium')
air.df.show()

 Temp level = low

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|    false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|    false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|    false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|    false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|    false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|    false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|    false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|    false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|    false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|    false|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|    false|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|    false|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|    false|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|    false|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|    false|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|    false|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|    false|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|    false|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|     true|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
only showing top 20 rows


 RH level = high

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|    false|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|    false|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|    false|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|    false|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|    false|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|    false|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|    false|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|    false|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|    false|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|     true|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|     true|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|    false|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|    false|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|    false|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|    false|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|     true|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|    false|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|    false|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|     true|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|     true|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
only showing top 20 rows


 Temp level = medium
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|     true|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|     true|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|     true|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|     true|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|     true|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|     true|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|     true|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|     true|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|     true|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|     true|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|     true|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|     true|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|     true|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|     true|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|     true|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|     true|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|     true|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|     true|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|    false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|    false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
only showing top 20 rows
Column is not a string
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|_c0|     Date|               Time|CO(GT)|PT08.S1(CO)|NMHC(GT)|C6H6(GT)|PT08.S2(NMHC)|NOx(GT)|PT08.S3(NOx)|NO2(GT)|PT08.S4(NO2)|PT08.S5(O3)|   T|  RH|    AH|T_level|RH_level|num_check|null_check|str_check|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
|  0|3/10/2004|2026-03-22 18:00:00|   2.6|       1360|     150|    11.9|         1046|    166|        1056|    113|        1692|       1268|13.6|48.9|0.7578| medium|  medium|     true|     false|     true|
|  1|3/10/2004|2026-03-22 19:00:00|   2.0|       1292|     112|     9.4|          955|    103|        1174|     92|        1559|        972|13.3|47.7|0.7255| medium|  medium|     true|     false|     true|
|  2|3/10/2004|2026-03-22 20:00:00|   2.2|       1402|      88|     9.0|          939|    131|        1140|    114|        1555|       1074|11.9|54.0|0.7502| medium|  medium|     true|     false|     true|
|  3|3/10/2004|2026-03-22 21:00:00|   2.2|       1376|      80|     9.2|          948|    172|        1092|    122|        1584|       1203|11.0|60.0|0.7867| medium|  medium|     true|     false|     true|
|  4|3/10/2004|2026-03-22 22:00:00|   1.6|       1272|      51|     6.5|          836|    131|        1205|    116|        1490|       1110|11.2|59.6|0.7888| medium|  medium|     true|     false|     true|
|  5|3/10/2004|2026-03-22 23:00:00|   1.2|       1197|      38|     4.7|          750|     89|        1337|     96|        1393|        949|11.2|59.2|0.7848| medium|  medium|    false|     false|     true|
|  6|3/11/2004|2026-03-22 00:00:00|   1.2|       1185|      31|     3.6|          690|     62|        1462|     77|        1333|        733|11.3|56.8|0.7603| medium|  medium|    false|     false|     true|
|  7|3/11/2004|2026-03-22 01:00:00|   1.0|       1136|      31|     3.3|          672|     62|        1453|     76|        1333|        730|10.7|60.0|0.7702| medium|  medium|    false|     false|     true|
|  8|3/11/2004|2026-03-22 02:00:00|   0.9|       1094|      24|     2.3|          609|     45|        1579|     60|        1276|        620|10.7|59.7|0.7648| medium|  medium|    false|     false|     true|
|  9|3/11/2004|2026-03-22 03:00:00|   0.6|       1010|      19|     1.7|          561|   NULL|        1705|   NULL|        1235|        501|10.3|60.2|0.7517| medium|    high|     NULL|     false|     true|
| 10|3/11/2004|2026-03-22 04:00:00|  NULL|       1011|      14|     1.3|          527|     21|        1818|     34|        1197|        445|10.1|60.5|0.7465| medium|    high|    false|     false|     true|
| 11|3/11/2004|2026-03-22 05:00:00|   0.7|       1066|       8|     1.1|          512|     16|        1918|     28|        1182|        422|11.0|56.2|0.7366| medium|  medium|    false|     false|     true|
| 12|3/11/2004|2026-03-22 06:00:00|   0.7|       1052|      16|     1.6|          553|     34|        1738|     48|        1221|        472|10.5|58.1|0.7353| medium|  medium|    false|     false|     true|
| 13|3/11/2004|2026-03-22 07:00:00|   1.1|       1144|      29|     3.2|          667|     98|        1490|     82|        1339|        730|10.2|59.6|0.7417| medium|  medium|    false|     false|     true|
| 14|3/11/2004|2026-03-22 08:00:00|   2.0|       1333|      64|     8.0|          900|    174|        1136|    112|        1517|       1102|10.8|57.4|0.7408| medium|  medium|     true|     false|     true|
| 15|3/11/2004|2026-03-22 09:00:00|   2.2|       1351|      87|     9.5|          960|    129|        1079|    101|        1583|       1028|10.5|60.6|0.7691| medium|    high|     true|     false|     true|
| 16|3/11/2004|2026-03-22 10:00:00|   1.7|       1233|      77|     6.3|          827|    112|        1218|     98|        1446|        860|10.8|58.4|0.7552| medium|  medium|     true|     false|     true|
| 17|3/11/2004|2026-03-22 11:00:00|   1.5|       1179|      43|     5.0|          762|     95|        1328|     92|        1362|        671|10.5|57.9|0.7352| medium|  medium|    false|     false|     true|
| 18|3/11/2004|2026-03-22 12:00:00|   1.6|       1236|      61|     5.2|          774|    104|        1301|     95|        1401|        664| 9.5|66.8|0.7951|    low|    high|     true|     false|    false|
| 19|3/11/2004|2026-03-22 13:00:00|   1.9|       1286|      63|     7.3|          869|    146|        1162|    112|        1537|        799| 8.3|76.4|0.8393|    low|    high|     true|     false|    false|
+---+---------+-------------------+------+-----------+--------+--------+-------------+-------+------------+-------+------------+-----------+----+----+------+-------+--------+---------+----------+---------+
only showing top 20 rows

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv
26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

**Summarization method examples**

Below I've given some examples of the summarization methods.

- This summarizes all the numeric columns since no column was entered in the method call.

In [176]:
air.col_minmax()

26/03/22 21:14:08 WARN CSVHeaderChecker: CSV header does not conform to the schema.
 Header: , CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
 Schema: _c0, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH
Expected: _c0 but found:
CSV file: file:///home/jupyter-ljzier@ncsu.edu/ST-554-project2-repo/data/air.csv

         col_name       min       max
0             _c0    0.0000  9356.000
1          CO(GT)    0.1000    11.900
2     PT08.S1(CO)  647.0000  2040.000
3        NMHC(GT)    7.0000  1189.000
4        C6H6(GT)    0.1000    63.700
5   PT08.S2(NMHC)  383.0000  2214.000
6         NOx(GT)    2.0000  1479.000
7    PT08.S3(NOx)  322.0000  2683.000
8         NO2(GT)    2.0000   340.000
9    PT08.S4(NO2)  551.0000  2775.000
10    PT08.S5(O3)  221.0000  2523.000
11              T   -1.9000    44.600
12             RH    9.2000    88.700
13             AH    0.1847     2.231

- Now I summarize a few diffent numeric columns to show functionality. This includes 2 examples of grouped levels

In [177]:
air.col_minmax("CO(GT)")

  col_name  min   max
0   CO(GT)  0.1  11.9

In [178]:
air.col_minmax("C6H6(GT)", "T_level")

   col_name T_level  min   max
0  C6H6(GT)     low  0.1  63.7
1  C6H6(GT)    high  1.0  52.1
2  C6H6(GT)  medium  0.2  50.8

In [179]:
air.col_minmax("C6H6(GT)", "RH_level")

   col_name RH_level  min   max
0  C6H6(GT)      low  0.9  38.4
1  C6H6(GT)     high  0.5  52.1
2  C6H6(GT)   medium  0.1  63.7

In this case I call a non-numeric column

In [180]:
air.col_minmax("T_level")

Column T_level is not numeric

Finally, I will report the counts associated with one or two string columns.
- Below are the temporature counts for each category.

In [187]:
air.str_count('T_level')

  T_level  count
0     low   1683
1    high   3711
2  medium   3584
3    NULL    379

- Below are the relative humidity counts for each category.

In [188]:
air.str_count('RH_level')

  RH_level  count
0      low   1441
1     high   2633
2   medium   4917
3     NULL    366

In [193]:
result=air.str_count('T_level', 'RH_level')
result.sort_values(['T_level', 'RH_level'])

   T_level RH_level  count
6     NULL     NULL    366
4     NULL   medium     13
1     high     high    375
8     high      low   1186
5     high   medium   2150
0      low     high    771
7      low      low     33
10     low   medium    879
3   medium     high   1487
9   medium      low    222
2   medium   medium   1875

In [195]:
#result['T_level'] = pd.Categorical(result['T_level'], categories=['low', 'medium', 'high'], ordered=True)
#result['RH_level'] = pd.Categorical(result['RH_level'], categories=['low', 'medium', 'high'], ordered=True)
#result.sort_values(['T_level', 'RH_level'])